### ISSUE TITLE
Options for HTTP queries

### ISSUE THREAD

**Issue by lionep** [louislam/uptime-kuma#11]
Hey, nice project there !

Just a feature idea : it would be nice to have the possibility to customize the HTTP(s) query, with custom headers, method, body, to monitor private APIs for instance.

**Comment by JeremyKennedy** [comment]
Definitely need this one. I have many services behind Authelia, and I don't think those can be checked without passing a custom authentication header.

**Comment by Hyurt** [comment]
I'd even add the ability to allow certain response code 
401 - 403 can be acceptable response code in some use case

**Comment by aHVzY2g** [comment]
@JeremyKennedy FYI you can allow the kuma IP to bypass in authelia config.

```
  rules:
    - domain: "*.example.com"
      policy: bypass
      networks:
        - uptime_monitor

    - domain: "*.example.com"
      policy: two_factor
```
