### ISSUE TITLE
Traefik and Uptime Kuma

### ISSUE THREAD

**Issue by exilewolf** [louislam/uptime-kuma#1111]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi! 

Loving this tool allot but appears I can not monitor https sites that are behind a Traefik proxy,  Not sure what is going on but I do get the error in the container log of "Failing: socket hang up" Is there any tips or tricks to get this working ? I found plenty of docs on how to have Kuma behind Traefik but not the other way around. 

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Brave

### 🐋 Docker Version

Docker version 20.10.12

**Comment by beatkind** [comment]
Hi @exilewolf,

I am not sure what kind of setup you have. I assume that you have Uptime Kuma running as docker container behind a Traefik Proxy. When you are now trying to monitor any HTTPS site, you are getting the error?

**Comment by oskapt** [comment]
@exilewolf I'm running Uptime Kuma behind Traefik, and I'm also using it to monitor local and remote sites that are behind Traefik. I'm also the Head of Developer Relations at Traefik Labs. If you can share some specifics about your environment, I'll help get you sorted.

**Comment by pkleingu** [comment]
@oskapt 
i have the same problem this is my config, it works with heimdall but not with uptime kuma.
example from https://www.youtube.com/watch?v=liV3c9m_OX8&t=5s

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.11.1-alpine
    container_name: uptime-kuma
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./data:/app/data
    ports:
      - 3001:80
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.entrypoints=http"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.local.<owndomain>.nl`)"
      - "traefik.http.middlewares.uptime-kuma-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.uptime-kuma.middlewares=uptime-kuma-https-redirect"
      - "traefik.http.routers.uptime-kuma-secure.entrypoints=https"
      - "traefik.http.routers.uptime-kuma-secure.rule=Host(`uptime-kuma.local.<owndomain>.nl`)"
      - "traefik.http.routers.uptime-kuma-secure.tls=true"
      - "traefik.http.routers.uptime-kuma-secure.service=uptime-kuma"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
#      - 'traefik.http.routers.uptime-kuma-secure.middlewares=authelia@docker'
networks:networks:
  proxy:
    external: true

**Comment by rezzorix** [comment]
> ports:
> \- 3001:80

You changed the internal port of uptime Kuma to port 80.
I would say thats the error.

Leave the Kuma internal port at 3001 and you can change the outfacing port to another one.

**Comment by exilewolf** [comment]
Sorry about the delay in responding bust time of year :) I am running Kuma on Docker and behind traefik with HTTPS and a valid cert.  I can monitor other servers with out issue but I am tiring to monitor another docker server that also has all its services behind traefik and this is where it is failing.  

I love both products so just seeing if I can get them to play the way I had hoped :)

**Comment by rezzorix** [comment]
Again, not sure how this works for you, but your yml code shows for uptime-kuma the outside port 3001 and inside 80...

It should be 3001:3001 or if you wanna run it at 80, then it should be 80:3001 not 3001:80 - however, I think if traefik runs on the same machine, then traefik is monitoring the port 80 and 443 if I am not wrong...

But maybe I am overlooking something here?
Or have you made changes to anything else in the docker-files?

**Comment by oskapt** [comment]
@pkleingu as @rezzorix pointed out, it appears that you're telling Traefik to connect to Uptime Kuma on port 80, when it's actually listening on port 3001. This happens in your reversed `ports` directive (change that to `80:3001` and then again when you tell Traefik to connect to Uptime Kuma on port 80 in the labels down below. Try changing that to `3001` and tell us if you can reach Uptime Kuma. You can also remove the `ports` directive entirely, because you're not publishing a port on the host itself. You're connecting to it through Traefik, and the container will be listening on 3001 inside of the `proxy` network.

**Comment by exilewolf** [comment]
I believe @pkleingu's issue is a separate issue from the one I am having. I have no issues with Access to Kuma. My issue is with Kuma monitoring devices that are behind a traefik proxy.

**Comment by oskapt** [comment]
@exilewolf i made a sample environment that should be close to what you have, minus the TLS configuration.

- i spun up a Traefik instance, an instance of Uptime Kuma, and an instance of the famous "catapp" application. 
- i configured my local DNS environment to point `uptime-kuma.test.monach.us` and `catapp.test.monach.us` to the node where all of this is running
- i tested that i could reach catapp and uptime-kuma (and the traefik dashboard, which is running in insecure mode for this test) from outside of the environment (from a different machine)
- i then configured Uptime Kuma to monitor the catapp application
- everything just works

![image](https://user-images.githubusercontent.com/171292/148290665-4975d5d0-5448-4325-9df2-6d94b9ec7554.png)

i'm attaching my config below - please take a look and compare it to your own to see if something is different. maybe your Uptime Kuma container isn't resolving DNS for the application you want to monitor? or maybe there's a missing label? a network/firewall ACL preventing communication?

when i have a problem w/ Uptime Kuma saying something is down when i think it should be able to see it, i shell into the container and insatll curl with `apt-get update && apt-get -qq install curl` so that i can run tests directly from inside the container and get better output for debugging. use `curl -I` to just get headers and look at the response code. you can also test the TLS part with `openssl s_client -connect x.x.x.x:443 -servername foo.whatever.com` to make sure there's not a certificate issue. 

finally, you can put Traefik into debug mode and see if maybe it's having a different problem altogether. 

**`docker-compose.yml`**
```
version: '3.1'

services:
  traefik:
    # The latest official supported Traefik docker image
    image: traefik:v2.5
    # Enables the Traefik Dashboard and tells Traefik to listen to docker
    # enable --log.level=INFO so we can see what Traefik is doing in the log files
    ports:
      # Exposes port 80 for incoming web requests
      - "80:80"
      - "443:443"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml

# Add the catapp service
  catapp:
     # A Random Cat GIF generator application
     image: mikesir87/cats:1.0
     # We set a label to tell Traefik to assign a hostname to the new service
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catapp.rule=Host(`catapp.test.monach.us`)"
      - "traefik.http.routers.catapp.entrypoints=web"
      - "traefik.http.routers.catapp.service=catapp"
      - "traefik.http.services.catapp.loadbalancer.server.port=5000"

  uptime-kuma:
    image: louislam/uptime-kuma:1.11.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.test.monach.us`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=web"
      - "traefik.http.routers.uptime-kuma.service=uptime-kuma"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
    volumes:
      - ./data:/app/data
```

**`traefik.yml`**
```
################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
################################################################
# Traefik Logging
################################################################
log:
  level: INFO

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
 ```
