### ISSUE TITLE
Fresh container: SQLITE database locked

### ISSUE THREAD

**Issue by cinderblockgames** [louislam/uptime-kuma#127]
I'm trying to get this up for the first time, but I'm running into sqlite issues right off the bat:

```
,
> uptime-kuma@1.0.7 start-server /app,
> node server/server.js,
,
Welcome to Uptime Kuma ,
Importing libraries,
Version: 1.0.7,
Creating express and socket.io instance,
Connecting to Database,,
d,
Your database version: 0,
test database version: 3,
Database patch is needed,
Backup the db,
Patching ./db/patch1.sql,
Closing DB,
SQLite closed,
Patch db failed!!! Restoring the backup,
[Error: COMMIT - SQLITE_BUSY: database is locked] {,
  errno: 5,,
  code: 'SQLITE_BUSY',
},
Start Uptime-Kuma failed due to patch db failed,
Please submit the bug report if you still encounter the problem after restart: https://github.com/louislam/uptime-kuma/issues,
npm ERR! code ELIFECYCLE,
npm ERR! errno 1,
npm ERR! uptime-kuma@1.0.7 start-server: `node server/server.js`,
npm ERR! Exit status 1,,
 ,
npm ERR! Failed at the uptime-kuma@1.0.7 start-server script.,
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.,
,
npm ERR! A complete log of this run can be found in:,
npm ERR!     /root/.npm/_logs/2021-07-30T14_22_41_684Z-debug.log,
```

Here's my docker-compose:

```
version: '3.8'

services:

  uptime-kuma:
    image: 'louislam/uptime-kuma'
    volumes:
      - '/run/homelab/monitoring/uptime-kuma:/app/data'
    networks:
      - traefik
      - monitoring-private
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.arch == x86_64]
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik'
        - 'traefik.http.routers.uptime-kuma.rule=Host(`monitor.homelab.express`)'
        - 'traefik.http.routers.uptime-kuma.entrypoints=web-secure'
        - 'traefik.http.routers.uptime-kuma.tls'
        - 'traefik.http.services.uptime-kuma.loadbalancer.server.port=3001'

networks:
  traefik:
    external: true
  monitoring-private:
    external: true
```

Any thoughts?  The container creates `kuma.db` and `kuma.db.bak0` in its `/app/data` directory.

EDIT:  For anyone who finds this later:

```
  uptime-kuma:
    image: 'louislam/uptime-kuma'
    command: |
      /bin/sh -c "cp /mnt/host/kuma.db /app/data/kuma.db && npm run start-server"
    volumes:
      - '/run/homelab/monitoring/uptime-kuma:/mnt/host'
```

This will copy the database from the host into the container before starting the monitoring app.  You have to run `cp /app/data/kuma.db /mnt/host/kuma.db` to back up the database, but, since I don't care about history, I only have to do that when I add new sites to monitor.  Not ideal, but it works.
