### ISSUE TITLE
Failing: ping: socket: Operation not permitted

### ISSUE THREAD

**Issue by procheeseburger** [louislam/uptime-kuma#1347]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When I setup Ping Monitor I get the following error: Failing: ping: socket: Operation not permitted

If I look at the docker logs I see the same for every monitor I've set:

Monitor #1 'PING - GOOGLE': Failing: ping: socket: Operation not permitted

and my docker-compose:

---
```
version: "3.1"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ~/vm/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    networks:
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_RAW

networks:
  proxy:
    external: true
```

### 🐻 Uptime-Kuma Version

Version: 1.12.1

### 💻 Operating System and Arch

ubuntu 20.04

### 🌐 Browser

brave

### 🐋 Docker Version

20.10.12

### 🟩 NodeJS Version

Your Node.js version: 14
