### ISSUE TITLE
Configure monitors using config file (like Heartbeat)

### ISSUE THREAD

**Issue by mchudinov** [louislam/uptime-kuma#1354]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

An ability to configure monitors using configuration JSON/XML/YAML/INI/whatever file, like Heartbeat does.

Heartbeat monitor config example:
```
heartbeat.monitors:
- type: icmp
  id: ping-myhost
  name: My Host Ping
  hosts: ["myhost"]
  schedule: '*/5 * * * * * *'
- type: tcp
  id: myhost-tcp-echo
  name: My Host TCP Echo
  hosts: ["myhost:777"]  # default TCP Echo Protocol
  check.send: "Check"
  check.receive: "Check"
  schedule: '@every 5s'
- type: http
  id: service-status
  name: Service Status
  service.name: my-apm-service-name
  hosts: ["http://localhost:80/service/status"]
  check.response.status: [200]
  schedule: '@every 5s'
```

### ✔️ Solution

The configuration file is injected into Docker image while uptime-kuma start and immediately taken into action by uptime-kuma. 
Such config file can be created and automatically deployed as part of script. Then uptime-kuma can be used for uptime of complex automated deployments like GitLab.
