### ISSUE TITLE
Unable to Setup Mail Notification Server

### ISSUE THREAD

**Issue by shawn3308** [louislam/uptime-kuma#1419]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

![image](https://user-images.githubusercontent.com/60691117/160237230-5c57c234-294d-4d0b-945a-80d96f517c40.png)

i am getting this error

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

windows

### 🌐 Browser

google chrome 

### 🟩 NodeJS Version

16.14.0

**Comment by louislam** [comment]
It is a dns lookup timeout issue. You can try to ping it first.

**Comment by shawn3308** [comment]
this comes when i hit the test button

**Comment by shawn3308** [comment]
can see it

**Comment by shawn3308** [comment]
hello ??

**Comment by procheeseburger** [comment]
Can you post your config? I have email alerts working just fine.

**Comment by shawn3308** [comment]
@procheeseburger

**Comment by procheeseburger** [comment]
What does your docker config look like? specifically did you set a nameserver? Also what does your alert config look like? 

```
---
version: "3.9"

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - ${FILE1}:/app/data
    ports:
      - 3001:3001
    environment:
      - "NAME_SERVERS=${NAME_SERVERS}"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
```

 
Here is the alert I get:

![image](https://user-images.githubusercontent.com/32914889/161056635-17950282-8390-46a2-b114-b6201529be75.png)
