### ISSUE TITLE
[OpenShift] Support Thread

### ISSUE THREAD

**Issue by k3rnelpan1c-dev** [louislam/uptime-kuma#1531]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

As part of #1286 ppl asked if I could share my config to get Uptime Kuma running on OpenShift.
So to provide a starting point for everyone interested this "question"/help issue now exists.

So for various reasons I ended up creating my own Docker image based on the official uptime-kuma image, but long story short:
1. I needed to for work (due to base image policy)
2. I wanted to have full control over how the image and configure how the permissions are set (according to the [RedHat Docs](https://docs.openshift.com/container-platform/4.10/openshift_images/create-images.html#images-create-guide-openshift_create-images))

<details>
  <summary>Containerfile</summary>

```Dockerfile
FROM docker.io/louislam/uptime-kuma:1.11.4-debian AS app-src

FROM docker.io/node:14-bullseye-slim

ARG UID=3310
ARG GID=3310

COPY --from=app-src /app /app

RUN apt-get update -qqy \
    && apt-get install --no-install-recommends -qqy \
        python3 python3-pip python3-cryptography python3-six python3-yaml python3-click python3-markdown python3-requests python3-requests-oauthlib \
        sqlite3 iputils-ping util-linux dumb-init wget curl ca-certificates bash \
    && pip3 --no-cache-dir install apprise==0.9.7 \
    && rm -rf /var/lib/apt/lists/* \
    \
    && addgroup --system --gid ${GID} uptime-kuma || true \
    && adduser --system --disabled-login --ingroup uptime-kuma --no-create-home --home /nonexistent --gecos "uptime-kuma" --shell /bin/false --uid ${UID} uptime-kuma || true \
    && mkdir /app/data \
    && chown -R uptime-kuma:0 /app \
    && chmod -R g=u /app

WORKDIR /app
USER uptime-kuma
EXPOSE 3001
VOLUME ["/app/data"]
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["node", "server/server.js"]
```

> Note: 
> * Yes this is a tat outdated but the basics should work with new versions too.
> * Yes this version may copy over the `entrypoint.sh` as part of copying the `/app` folder, but am not using it. This is  due to OpenShift not permitting running as root/privileged user unless explicitly permitted and the script relying on that to change permissions on the persistent files.
</details>

### Deployment

I hacked together a very basic Helm (3.x+) Chart to deploy a StatefullSet to our OpenShift cluster with a service and a Route. You can find that here: https://github.com/k3rnelpan1c-dev/uptime-kuma-helm

I will try and answer any questions and feedback to my best abilities and as time allows. If this issue violates the contribution guidelines in any way that I overlooked then please feel free to close this and my apologies in that case.

### 🐻 Uptime-Kuma Version

1.11.4

### 💻 Operating System and Arch

OpenShift 4.x

### 🌐 Browser

Firefox 99

### 🐋 Docker Version

cri-o

### 🟩 NodeJS Version

14.19.1

**Comment by openstep** [comment]
Is there now a fixed version of uptime-kuma docker image? If not, could you @k3rnelpan1c-dev share the one you built?

**Comment by k3rnelpan1c-dev** [comment]
Well, I did share the `Containerfile` that I used to build my OpenShift compatible image in the issue text :thinking: 
But I might as well setup a tiny GitHub action CI in my linked PoC Helm Chart repo to build it :man_shrugging:

**Comment by openstep** [comment]
Hi,
We also built this finally, but getting websocket errors like: 
`Cannot connect to the socket server. [Error: timeout] Reconnecting...`
our service on OpenShift level is like

```
kind: Service
apiVersion: v1
metadata:
  name: example
  namespace: uptime-kuma
spec:
  ports:
    - name: webservice
      protocol: TCP
      port: 80
      targetPort: webservice
  selector:
    app: uptime-kuma
  clusterIP: xxxxx
  clusterIPs:
    - xxxxx
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
```
and route is like

```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  host: uptime-kuma.xxxxx
  to:
    kind: Service
    name: example
    weight: 100
  port:
    targetPort: webservice
  wildcardPolicy: None
```
What could be wrong?

**Comment by k3rnelpan1c-dev** [comment]
Okay, where exactly do you get `[Error: timeout] Reconnecting...` when trying to connect to uptime-kuma or with uptime-kuma trying to ping som other service?

**Comment by openstep** [comment]
It was a stupid squid proxy error over vpn. Sorry, this question could be deleted.

**Comment by k3rnelpan1c-dev** [comment]
Ah yes proxy issues, my favourite :sweat_smile: 

btw. hacked something together in terms of CI and with an updated Kuma version:
* [Source](https://github.com/k3rnelpan1c-dev/uptime-kuma-helm/blob/main/container/Containerfile)
* [Quay](https://quay.io/repository/k3rnel-pan1c/uptime-kuma?tab=info)

@louislam, hope you are alright with me repackaging the image this way, if not please let me know and I will purge its existence but keep the sources available.

**Comment by louislam** [comment]
It is ok. 

If you think it is stable, you could also add it into `How to Install` section as an unofficial way by creating a pull request.

https://github.com/louislam/uptime-kuma-wiki/blob/master/%F0%9F%94%A7-How-to-Install.md

**Comment by k3rnelpan1c-dev** [comment]
Thank you :slightly_smiling_face: 

I will keep on testing a bit more and will then give it another thought.
Depending on how stable my repackage CI is going to be I may omit my repackage in that though, as I want to avoid guiding ppl to an install path that I would not be able to maintain (even if it is just unofficial).

Thank you for this great tool btw :+1:

**Comment by k3rnelpan1c-dev** [comment]
well, went ahead and finally opened https://github.com/louislam/uptime-kuma-wiki/pull/11, as I am happy with my automated workflow to re-bundle.
Additionally, it helps everyone wanting/needing a rootless uptime-kuma image, as it is implicitly required by OpenShift.

**Comment by nicolasmontesi** [comment]
if I can dare to advise, it is possible to simplify the part relating to the assignment of permissions. In fact, you just need to add the following without the creation of a new user/group.
```
RUN chgrp -R 0 directory && \    
        chmod -R g=u directory

USER 1001
```

Explanation from the doc: The user account that runs the container is always a member of the root group, hence the container can read and write to this directory. The root group does not have any special permissions (unlike the root user) which minimizes security risks with this configuration. The g=u argument from the chmod command makes the group permissions equal to the owner user permissions, which by default are read and write. You can use the g+rwX argument with the same results. The user 1001 instead is the Red Hat convention. 

I modified the Dockerfile accordingly and works like a charm.

**Comment by k3rnelpan1c-dev** [comment]
overall you right, but one thing that I observed (not with uptime IIRC, but other NodeJS and Python Apps) is that they sometimes rely on a writable home directory, which is an easy fix if you set the envVar `HOME` to a volume or emptyDir.
However, I generally added the extra user for other container runtimes that don't act like OpenShift (running as arbitrary UID) so they have a user to their UID uptime runs as. (is it overkill, maybe :man_shrugging:, but it works)

**Comment by ArthurVardevanyan** [comment]
@k3rnelpan1c-dev's Container Image works perfectly for me on OKD/OCP 4.11 with the Restricted-v2 SCC.

Ping doesn't work, but I don't use it anyways.

```yaml
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: N/A in Openshift
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
```
