### ISSUE TITLE
Error getaddrinfo EAI_AGAIN xxx.com

### ISSUE THREAD

**Issue by quick-tutoriel** [louislam/uptime-kuma#1697]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

It is impossible to resolve a domain name through the Uptime-Kuma container.

### 👟 Reproduction steps

It is sufficient to add a new probe or on an existing probe.

### 👀 Expected behavior

impossible to monitor my websites

### 😓 Actual Behavior

What actually happen?

### 🐻 Uptime-Kuma Version

1.16.0

### 💻 Operating System and Arch

Linux container

### 🌐 Browser

Chrome Version 95.0.4638.69 (Build officiel) (x86_64)

### 🐋 Docker Version

Docker version 20.10.16, build aa7e414

**Comment by SanderGit** [comment]
Having the same issue intermittently running in docker on a Synology device. Other functions are working fine.
Using 8.8.8.8 and 8.8.4.4 on Synology. 
Issue #1302 would be a nice potential workaround for this.

**Comment by martinr92** [comment]
Have the same problem right now. Running version 1.17.1 using docker.

**Comment by EVOTk** [comment]
Specifying 2 dns in the configuration of my container solved the problem for me.

### In docker-compose.yml :
```
dns:
  - <IP_DNS_1>
  - <IP_DNS_2>
```
Exemple : 
```
version: 3.3
services:
    uptime-kuma:
        restart: always
        ports:
            - 3001:3001
        volumes:
            - uptime-kuma:/app/data
        dns:
            - 1.0.0.1
            - 1.1.1.1
        container_name: uptime-kuma
        image: louislam/uptime-kuma:1
```

### In docker run :
```
--dns=<IP_DNS_1> --dns=<IP_DNS_2>
```
Exemple : 
```
docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --dns=1.0.0.1 --dns=1.1.1.1 --name uptime-kuma louislam/uptime-kuma:1
```
