### ISSUE TITLE
How to Let Uptime Kuma check status page behind Authelia? 

### ISSUE THREAD

**Issue by masterwishx** [louislam/uptime-kuma#1746]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How to Let Uptime Kuma check status page behind Authelia using Nginx Proxy Manager .
Becouse of authelia in NPM its redirect to auth.mysite.com but i need to check photo.mysite.com.
can i somehow configure Kuma or it should be done in NMP to avoid redirect when GET come from kuma.mysite.com ?
how to do it in nginx ?

### 🐻 Uptime-Kuma Version

Lasted

### 💻 Operating System and Arch

Unraid Linux x64

### 🌐 Browser

Chrome

**Comment by daeho-ro** [comment]
I think there are two ways to achive this.
- Use the internal hostname or ip when the uptime kuma is located at the same network.
-  By using the custom nginx configuration option of the nginx proxy manager, you can expose some path without authentication step.

**Comment by masterwishx** [comment]
> Use the internal hostname or ip

its good idea but its more like to check if container is running  , but if some other problem exist in cloudflare  or some other 
its better to check if www.mysite.com is avalible.
what custom nginx config i can use for example ?

**Comment by daeho-ro** [comment]
Oops, there is well constructed access control function in authelia, see the [docs](https://www.authelia.com/docs/configuration/access-control.html)  .

**Comment by masterwishx** [comment]
> Oops

Thanks its what i need i can add also proxy cloudflare ips but dont know what the right way to add kuma method GET ( "Uptime-Kuma/1.17.1" "-") or better some other methods ?

**Comment by londontechbytes** [comment]
> > Oops
> 
> Thanks its what i need i can add also proxy cloudflare ips but dont know what the right way to add kuma method GET ( "Uptime-Kuma/1.17.1" "-") or better some other methods ?

@masterwishx I can help you with this. 

Inside your Uptime Kuma, you want to change the monitor type from "HTTPS" to "Push", this will essentially make it work in the reverse order. You will be given a unique URL. This is uptime kuma hosting it's own Push Server essentially. 

The next step is to go to your other computer, hosted elsewhere, and set up a cron job in linux or scheduled task in windows to essentially go to that unique url every 60 sec. basically, your calling out to uptime kuma, rather than allow uptime to call into that project and get hung up on the authelia wall. 

here is an example: Add this into a Cron Job
you can do a curl -s https://status.techbytes.ca/api/push/VolAP8jfYR?msg=OK&ping= (this is a fake url i made to show you, replace this with your URL)

hopefully this helps you out :)

Chris
TechBytes.ca

**Comment by masterwishx** [comment]
> I can help you with this.

Thanks i will try it .

**Comment by masterwishx** [comment]
Is anyone found the easy way for it?

**Comment by LunaUrsa** [comment]
This issue is the first result for "uptime kuma authelia", so in the interest of future people: I solved this by going into the authelia volume/directory and modifying the access_control in the configuration.yml file. 

This new bolded block must appear before the two_factor entries; otherwise, it won't work.

```
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: authelia.example.tld
      policy: bypass
    **- domain: "*.example.tld"
      policy: bypass
      networks:
      - 'xx.xx.xx.xx/32' # My home IP. Use /32 for a single IP address
      - '192.168.0.0/16'   # My home network**
    - domain: "*.example.tld"
      policy: two_factor
    - domain: "example.tld"
      policy: two_factor
```

Hope this helps someone!
