### ISSUE TITLE
Clone repo for docker install?

### ISSUE THREAD

**Issue by zluckytraveler** [louislam/uptime-kuma#1761]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Do I need to clone the entire repo and add it to where the local volume is being mounted for a Docker install?

I've tried designated a local volume in the docker run command, but docker is still creating volumes on docker desktop, whenever I create the container, instead of using the local volume directory I have pointed out.

**Docker Run Command:**
docker run --name Server-Status -d --restart=unless-stopped -p 3001:3001 -v /Applications/Apps/Programs/Uptime-Kuma:/app/data louislam/uptime-kuma:1

https://imgur.com/a/PV1Ir8L

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

MacOS 11.6.7

### 🌐 Browser

Safari 15.5

### 🐋 Docker Version

4.9.0

**Comment by louislam** [comment]
I don't use MacOS, but I think it should be related:
https://stackoverflow.com/a/68495984/1097815

**Comment by daeho-ro** [comment]
What about using this docker compose file within the Document directory? For ex, `~/Documents/uptime-kuma/docker-compose.yml` and use the command `docker compose up -d`.

```
services:
  kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data
    restart: unless-stopped
```
