### ISSUE TITLE
Traefik reverse proxy with Kuma

### ISSUE THREAD

**Issue by Sloth-on-meth** [louislam/uptime-kuma#178]
hiya!

my current setup:

```
services:
  kuma:
    container_name: kuma
    image: louislam/uptime-kuma:1
    volumes:
      - /docker/kuma:/app/data
    ports:
      - 5577:3001
    labels:
      - traefik.enable=true
      - traefik.port=3001
      - traefik.frontend.rule=Host:kuma.DOMAIN.nl
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto = https
```
i can't get traefik to work this way. i just get a page not found .
