### ISSUE TITLE
Docker images status in local server and remote server

### ISSUE THREAD

**Issue by johnfelipe** [louislam/uptime-kuma#1811]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, New Notification, New Monitor, UI Feature

### 🔖 Feature description

i have a lot of docker container, images in local server and remotes servers, will be a good feature have method for monitor it

### ✔️ Solution

i havent solution, because is a request

**Comment by johnfelipe** [comment]
```
felipe@felipe:~$ sudo su
root@felipe:/home/felipe# cd
root@felipe:~# cd uptime-kuma/
root@felipe:~/uptime-kuma# docker pull louislam/uptime-kuma:1
1: Pulling from louislam/uptime-kuma
c32ce6654453: Already exists
866efb834763: Already exists
3009c2701a70: Already exists
704508b5309b: Already exists
11cc6386a88d: Already exists
50694b369ddf: Already exists
d47b92313a6b: Already exists
43eee6140fa4: Already exists
e878accd8693: Already exists
1b61d6b9fde3: Pull complete
Digest: sha256:080b34c0953f7f324731439c5e8000902d21622a44f7f01215aacbeaf741a30c
Status: Downloaded newer image for louislam/uptime-kuma:1
docker.io/louislam/uptime-kuma:1
root@felipe:~/uptime-kuma# docker stop uptime-kuma
uptime-kuma
root@felipe:~/uptime-kuma# docker rm uptime-kuma
uptime-kuma
root@felipe:~/uptime-kuma# docker run --add-host=host.docker.internal:host-gateway -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
c1bd0f57e2832f63147ba0e1d6a7a593fb92f7bd02c79a138815f1b70d7966db

```

![SNAG-0004](https://user-images.githubusercontent.com/428820/175051665-faba0080-91e9-4c62-b468-8929ab87b6d9.png)

still not working with

docker run `--add-host=host.docker.internal:host-gateway` -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1

and 

`/root/uptime-kuma/docker/docker-compose.yml`

i add this:

```
# Simple docker-composer.yml
# You can change your port or volume location

version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    extra_hosts:
      - "host.docker.internal:host-gateway"    
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always

```
