### ISSUE TITLE
Kubernetes integration with auto discovery

### ISSUE THREAD

**Issue by m4dm4rtig4n** [louislam/uptime-kuma#1932]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, New Monitor, Other

### 🔖 Feature description

The goal of the evolution would be to ensure that Uptime Kuma directly reads Ingress to self-configure HTTPs monitor.
And also with the possibility of creating custom config in the style:
```
apiVersion: uptime-kuma/v1
kind: tcp
metadata:
  name: home-assistant
spec:
  url: 192.168.1.100
  port: 8123
  retry: 0
  alerting:
    slack:
      webhook: https://.......
```
or 
```
apiVersion: uptime-kuma/v1
kind: ping
metadata:
  name: home-assistant
spec:
  url: 192.168.1.100
  retry: 0
  alerting:
    slack:
      webhook: https://.......
```

### ✔️ Solution

Create customressources uptime-kuma + RBAC
Uptime Kuma listen kubernetes API directly to read all configuration.
