### ISSUE TITLE
Clean up & organize issues going forward

### ISSUE THREAD

**Issue by rezzorix** [louislam/uptime-kuma#2042]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Currently there are 650+ open issues here on github. 

My suggestion is to clean that up by closing the resolved ones etc. 

Furthermore my suggestion is to add version labels/tags so that future issues are properly tagged (not only “help” etc)

@louisla

### 🐻 Uptime-Kuma Version

-

### 💻 Operating System and Arch

-

### 🌐 Browser

-

### 🐋 Docker Version

-

### 🟩 NodeJS Version

-

**Comment by gaby** [comment]
I added support for StaleBot a long time ago, but it was removed by the project owner. 

StaleBot: https://github.com/actions/stale
PR: https://github.com/louislam/uptime-kuma/pull/735

**Comment by rezzorix** [comment]
Ah damn... I typed my initial issue on mobile and somehow didnt tag Louis correctly.

@louislam may you have a look into the above? 😃

**Comment by louislam** [comment]
The bot closed feature-request unexpectedly, so I don't know why so I removed it. Free feel to fix it.

https://github.com/louislam/uptime-kuma/commit/e0175d0010c83e1783f03fc3f8bbed67494edcd5

**Comment by ThomasChr** [comment]
We could close many of those "I want to change XY but I don't know Javascript"-Issues.
They are a little bit annoying.

**Comment by rezzorix** [comment]
@louislam it closed "feature-request" in issues, because it was only on the exempt list for PR-labels; not on the Issue-labels exempt list.

Since the project is very popular, I also would suggest to reduce timings a bit:

90 days before stale
7 days after stale close

Here we go with an updated version:

```
name: 'Automatically close stale issues and PRs'
on:
  schedule:
    - cron: '0 0 * * *'
#Run once a day at midnight 

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-message: 'We are clearing up our old issues and your ticket has been open for 3 months with no activity. Remove stale label or comment or this will be closed in 7 days.'
          stale-pr-message: 'We are clearing up our old Pull Requests and yours has been open for 3 months with no activity. Remove stale label or comment or this will be closed in 7 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity.'
          days-before-stale: 90
          days-before-close: 7
          exempt-issue-labels: 'News,Medium,High,discussion,bug,doc,feature-request'
          exempt-pr-labels: 'awaiting-approval,work-in-progress,enhancement,feature-request'
          exempt-issue-assignees: 'louislam'
          exempt-pr-assignees: 'louislam'
```
