### ISSUE TITLE
Allow the user to configure multiple Cloudflare Tunnel Token

### ISSUE THREAD

**Issue by MAXOUXAX** [louislam/uptime-kuma#2130]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Currently, we can only define a single Cloudflare Tunnel token. While this might seem plenty for most of people, this can be limiting for some others.

Here's why this is limiting for me:
 - On my Cloudflare account, I've got all my domains
 - I've got access to another Cloudflare account through the "Invite members" section of Cloudflare, and I am an administrator
 - I cannot add a new domain to my existing tunnel, because only domains from my zone are displayed, so I cannot link my existing tunnel to a domain on the zone I am an administrator on
 - The solution I've found online coming from the Cloudflare community forums basically says that [you have to create a new tunnel](https://community.cloudflare.com/t/cloudflared-tunnel-multiple-services-domains-different-accounts-for-authentication-the-same-origin-server/336205)
 - Since Uptime Kuma only allows for a single token, I cannot create a tunnel directly from Uptime Kuma, and would have to set up a tunnel manually, which is a bit sketchy

### ✔️ Solution

The easiest solution would be to allow the user to define multiple tokens, and for each token, set up a new tunnel.

**Comment by louislam** [comment]
Alternatively, I would suggest that you could manage this by docker-compose with multiple tunnels.

For example:

```yml
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always

  tunnel1:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=<YOUR TOKEN 1>

  tunnel2:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=<YOUR TOKEN 2>
```
