### ISSUE TITLE
SAMEORIGIN environment variable not being respected

### ISSUE THREAD

**Issue by rachelf42** [louislam/uptime-kuma#2160]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

i am trying to display Uptime-Kuma through [Muximux](https://github.com/mescon/Muximux)
chrome returns the console error "Refused to display 'https://kuma.mediaserv.local/' in a frame because it set 'X-Frame-Options' to 'sameorigin'."
i have confirmed that `echo $UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN` returns 1 when run inside the container

docker-compose.yml:
```
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    network_mode: host
    dns: 192.168.1.77
    ports:
      - 3001:3001
    volumes:
      - /media/config/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Vancouver
      - PUID=1000
      - PGID=1000
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=1
    logging:
      driver: syslog
      options:
        syslog-facility: "daemon"
        tag: "docker/{{.Name}}"
```

NPM advanced tab:
```
  location / {
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   Host $host;
    proxy_pass         http://192.168.1.77:3001/;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }
```

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Ubuntu 20.04 x86 under VirtualBox 6.1

### 🌐 Browser

Chrome v106.0.5249.91

### 🐋 Docker Version

Docker version 20.10.14, build a224086349
