### ISSUE TITLE
Parse Error: Invalid header value char

### ISSUE THREAD

**Issue by cirrusflyer** [louislam/uptime-kuma#23]
Removed old Docker image and setup latest 1.0.1.  Added a check to a website that was successfully being checked prior.  Getting this error:

Parse Error: Invalid header value char

Have another site that's still working fine.  So this error is new with this new version.

**Comment by louislam** [comment]
I think it caused by invalid http response header rather than 1.0.1 itself, because 1.0.1 just added User-Agent and nothing else in this part.
 
Related issue:
https://github.com/nodejs/node/issues/27711

**Comment by cirrusflyer** [comment]
Thanks.  I wonder why it was working fine in earlier version.

**Comment by cirrusflyer** [comment]
I see the Incapsula WAF reference here as well, which is what we use.  Any way to make the changes others are suggesting to resolve this issue?

**Comment by adumont** [comment]
Same issue here for some webs.

**Comment by louislam** [comment]
You should report to Incapsula, because they are corrupted your http header. 
Uptime Kuma here to tell your that.

**Comment by cirrusflyer** [comment]
Just an update.  I spoke with Incapsula (Imperva) and they stated this:

"I suspect that this is being caused by our client classification cookie, which is a malformed cookie by design...The client classification cookie is just one of many different client classification methods that we use, so disabling it will not increase the security risk towards the site."

I also know that Uptime Robot, OhDear!, and others don't have this issue.  What's unique about Kuma?

**Comment by simmessa** [comment]
Hi there, 

for the people coming here for a fix I just wanted to add that if you're running uptime-kuma in docker container and you see this issue (maybe you're unlucky enough to be forced to monitor resources behing incapsula malformed cookies) you can quickly fix by launching the docker container with --insecure-http-parser like this:

```
docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1 node --insecure-http-parser server/server.js
```

Please make sure the --inescure-http-parser goes before the js file for this to work.

Hope it's useful to you all.

**Comment by adumont** [comment]
Just tested, --insecure-http-parser switch working for me. Thanks.

**Comment by henkisdabro** [comment]
Thanks @simmessa for the solution, much appreciated! Would it be possible to implement some type of "disregard malformed cookies" option on per-monitor level? That way we don't need to make the entire Uptime Kuma instance parse insecure HTTP headers, but rather only when really necessary.

**Comment by mitin20** [comment]
works perfectly behind imperva-incapsula sites using docker thanks!!! @simmessa @adumont 

BTW any idea how to include --insecure-http-parser on kubernetes manifest

**Comment by 3deep5me** [comment]
@mitin20 check this spec out on a k8s deployment:
```
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: uptime-kuma
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: uptime-kuma
    spec:
      containers: #use this down here
      - command:
        - node
        - --insecure-http-parser
        - server/server.js
        
```
