### ISSUE TITLE
Not respecting UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=1

### ISSUE THREAD

**Issue by Leah96xxx** [louislam/uptime-kuma#2452]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When launching Uptime Kuma from docker compose, it is not respecting UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=1

I have tried using both 1 and true, but it ignores both, still showing "Refused to display 'https://kuma.[mydomain]' in a frame because it set 'X-Frame-Options' to 'sameorigin'." in the Chrome console.

Here is what I have in my docker-compose.yml:
``` 
uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /home/leah/docker/uptime-kuma:/app/data
    ports:
      - 3001:3001
    environment:
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=1
    restart: always
```

### 👟 Reproduction steps

Launch Uptime Kuma as described above, check if iframe works, find error in console

### 👀 Expected behavior

iframe works

### 😓 Actual Behavior

Iframe refuses to connect and Chrome console reports "Refused to display 'https://kuma.[mydomain]' in a frame because it set 'X-Frame-Options' to 'sameorigin'."

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Raspberry PI OS Lite 11 (bullseye), RasPI 4 ARM v8

### 🌐 Browser

Google Chrome 108.0.5359.125

### 🐋 Docker Version

Docker 20.10.18
