### ISSUE TITLE
[Enhancement] Add an example docker-compose.yml file to the docs

### ISSUE THREAD

**Issue by ColaIan** [louislam/uptime-kuma#25]
as title :D

**Comment by TheGuyDanish** [comment]
Is that really necessary? Uptime-Kuma runs in a single container without any database dependencies. I don't see the reason to user docker-compose for a small application like this.

**Comment by ColaIan** [comment]
> Is that really necessary? Uptime-Kuma runs in a single container without any database dependencies. I don't see the reason to user docker-compose for a small application like this.

Hm 🤔I guess it might still be a good idea to have it as you would only need to run docker-compose up, which is more convenient than making a bash file with a docker run command, and imo docker-compose is easier to manage

**Comment by TheGuyDanish** [comment]
Again, not sure why you'd really want to. The oneliner in the README is quite simple, but you can get the job done with:
```yaml
version: "3.9"
services:
  app:
    image: louislam/uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - /opt/uptime-kuma:/app/data
```
