### ISSUE TITLE
How to add TLS certificates

### ISSUE THREAD

**Issue by Abdulhadiasa** [louislam/uptime-kuma#2675]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am running uptime-kuma in a docker container, I want to monitor a docker container running in a remote machine, I was able to generate the server certificates and create a TLS request with curl using the following command:
`curl https://<remote server ip>:2376/containers/json --cacert ca.cert --cert client.cert --key client.key`
and I received a json response with the running containers on the remote server.

How can I add my certificates (ca.cert, client.cert, client.key) so that uptime-Kuma can monitor the container?

this is my docker-compose file adjusted according to [#850](https://github.com/louislam/uptime-kuma/issues/850#issuecomment-1089808598)
```
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1-debian
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
      - ./uptime-kuma-data/data/certs:/certs:ro # I tried adding my certificates here
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: always
    environment:
        - UPTIME_KUMA_SSL_KEY=/app/data/certs/client.key
        - UPTIME_KUMA_SSL_CERT=/app/data/certs/client.cert
```
but after setting the environments, localhost:3001 stopped giving back a response

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

ubuntu 18.04

### 🌐 Browser

Firefox 108.0.2 (64-bit)
