### ISSUE TITLE
unable to verify the first certificate, no alarm with nocheck-tls-errors

### ISSUE THREAD

**Issue by rainerrose** [louislam/uptime-kuma#2768]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

A probably misconfigured web server returns  `Certificate Chain: Invalid` 

I've enabled in the Advanced Settings of the Monitor

- [X] Ignore TLS/SSL error for HTTPS websites
- [X] Certificate Expiry Notification

However, this does not cause an alarm even though the defined days have been exceeded (Settings->Notification->TLS Certtificate Expiry)
It is an official  TLS-Cert maybe intermediate Cert on Webserver  is missing, but I don't have access to the web server, so I can't change it.
When I disable the option ` Ignore TLS/SSL error for HTTPS websites` in the monitor throws `unable to verify the first certificate`  :cry: 

Is it a bug in uptime-kuma or  a misunderstanding on myself?

### 🐻 Uptime-Kuma Version

1.20.0

### 💻 Operating System and Arch

Centos 7

### 🌐 Browser

Edge Version 107.0+

### 🐋 Docker Version

23.0.0+

**Comment by louislam** [comment]
> intermediate Cert on Webserver is missing

I think you have answered.

My person opinion: 
If it is just a website, you can ignore it, as it won't be a problem in modern browsers. 
However, if it is an API, you should fix it, because for most programming languages, it cannot connect to your server. Uptime Kuma is an example, it is using Node.js.

**Comment by rainerrose** [comment]
Thank you for the quick response! :heart: 

> My person opinion: If it is just a website, you can ignore it, 

Unfortunately, I have to monitor the expiration of the certificate on this website. And the customer is resistant to advice, but it falls back on our team when it is broken (resp. expired)  The Website is visited only by browsers.
I had hoped that there would be analogous to `curl --insecure`  in Node.js :pray:  ?

If the answer is **Nope!** I'll have to write a small shell-Script :confused:  or a appointment on our digital calendar :shrug:

**Comment by chakflying** [comment]
I think a possible solution is to manually download the missing intermediate cert, and add it to node.js using the environment variable. ([example here](https://github.com/louislam/uptime-kuma/issues/1380))

**Comment by martinb07** [comment]
I have the same problem. I used the environment variable to set the path to the cert. It is a .cer-file from our internal CA in PEM format (it has an Begin Certificate and End Certificate)
How can I check that uptime kuma is recognizing the given cert?
The same cert is working on the server who should be monitored, by running traefik.

This is my docker-compose file:
`version: '2.0'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    mem_limit: 500m
    restart: always
    environment:
      - NODE_EXTRA_CA_CERTS = /app/data/certs/grafana-gwa.siemens.com.pem
    volumes:
      - /var/lib/docker/volumes/uptime-kuma/_data:/app/data
    ports:
      - 3001:3001`

When diving into the container, I see the cert is at the given location.

Thank you for your help.

**Comment by VecH** [comment]
I have the same problem when adding a host with HTTPS verification
`unable to verify first certificate`

Running in a docker container
`cat docker-compose.yml`
```
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - '3001:3001'
    restart: unless-stopped
```
OS: Ubuntu 24.04

How to add a certificate to a container so that everything works?

_on the host being checked, the Lets Encrypt certificate (updated a couple of days ago)_

**Comment by v-kamerdinerov** [comment]
@VecH I fixed this problem like that

- checked what certificate don't included in container (for me it Intermediate certificate  in ISRG Root X1 - https://crt.sh/?id=12396132904)
- rebuild image with new cert

```
FROM louislam/uptime-kuma:1
COPY e6.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates
```

Run kumma with NODE_EXTRA_CA_CERTS env variable

```
services:
  uptime-kuma:
    image: louislam/uptime-kuma:personal
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    environment:
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/e6.pem
      - TZ=Europe/Moscow
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
```
