### ISSUE TITLE
Timeout for services hosted on same host

### ISSUE THREAD

**Issue by RichardPiel** [louislam/uptime-kuma#277]
When I monitor domains that redirect to the same server as Kuma, I get a 
"Failing: timeout of 15000ms exceeded".

The domains are accessible, with a valid certificate.

If I monitor google.com, no problem.

Probably important information, the two services I'm trying to monitor are running under docker

**Info**
Uptime Kuma Version: 1.1.0
Using Docker?: Yes
OS: Debian
Browser: Chrome

**Comment by contagon** [comment]
I'm also running a similar setup with identical issues. All my services are on the same host each in docker containers, and I get that same error. I tried with uptime-kuma in and out of the same docker network as my services with identical results.

I don't think it's my services, if I monitor one of my services using the demo it works fine, so it's definitely related to being on the same host.

**Comment by gaby** [comment]
It could be something related to the way Portainer is launching the containers. Can you show the output of `docker ps -a` and `docker network ls`?

**Comment by heyitsforest** [comment]
I think I'm having this same issue. Uptime Kuma with 'network mode: host' or on another server works correctly but when it's on the same machine as my other apps/sites, it doesn't get a response from them. Other websites work fine. All containers are in the same default Docker network. I had the same issue before updating to the beta, just trying to solve it again now. 

If anyone has any suggestions please let me know, thanks!



---

**Troubleshooting:**
`docker exec uptime-kuma curl mysite.com` = timeout
`docker exec uptime-kuma ping mysite.com` = response
`docker run --rm curlimages/curl mysite.com` = response

---

**My setup:**
Linode Debian VPS - Docker - SWAG (Nginx) - Uptime Kuma

Docker compose:
```
  uptime-kuma:
    image: louislam/uptime-kuma:beta
    hostname: uptime-kuma
#    network_mode: host
    container_name: uptime-kuma
    environment:
      - NODE_ENV=development
    volumes:
      - /mnt/DockerVPS/volumes/uptime-kuma:/app/data
    ports:
      - 3002:3001
    restart: always
```
