### ISSUE TITLE
`Cannot connect to the socket server` through reverse proxy

### ISSUE THREAD

**Issue by filcuk** [louislam/uptime-kuma#2780]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Similar to #2753 & #2425, but I use Traefik 2 with Cloudflare.
I have read https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#traefik
WebSockets are enabled on Cloudflare.

I have setup base URL and enabled headers trust trough localhost:
![image](https://user-images.githubusercontent.com/1339532/218793023-d808ee55-fe3f-4434-a91b-65e4cdb6c37f.png)
![image](https://user-images.githubusercontent.com/1339532/218792879-c0477ccc-525a-425e-99b0-f4dbe6a6ef36.png)

Works fine on localhost, but fails through reverse proxy:
![image](https://user-images.githubusercontent.com/1339532/218782089-467c8fdc-43e5-4f51-b294-ffaa972bfc09.png)

Browser console:
```
Firefox can’t establish a connection to the server at wss://kuma.<redacted>/socket.io/?EIO=4&transport=websocket.
The connection to wss://kuma.<redacted>/socket.io/?EIO=4&transport=websocket was interrupted while the page was loading.
```

Docker compose:
```yaml
  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/appdata/kuma:/app/data
    networks:
      - reverse_proxy
    ports:
      - 3001:3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma-rtr.entrypoints=https"
      - "traefik.http.routers.kuma-rtr.rule=Host(`kuma.$DOMAINNAME0`)"
      - "traefik.http.routers.kuma-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.kuma-rtr.service=kuma-svc"
      - "traefik.http.services.kuma-svc.loadbalancer.server.port=3001"
```

I've tried adding the following, but it didn't help:
```yaml
  kuma:
  ...
    labels:
      ...
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.services.kuma-svc.loadbalancer.passhostheader=true"
      - "traefik.http.services.kuma-svc.loadbalancer.sticky=true"
```

### 🐻 Uptime-Kuma Version

1.20.0

### 💻 Operating System and Arch

DSM 7.1

### 🌐 Browser

Firefox 109.0

### 🐋 Docker Version

Docker 20.10.3

**Comment by soriyath** [comment]
@filcuk I could fix this using this piece of configuration:

```yaml
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https, wss"
```
Notice the comma, space, then `wss`.
Does it fix the problem on your infrastructure?

**Comment by filcuk** [comment]
I was going to test this solution, but I found out the page now loads through the reverse proxy.
No change in compose or proxy configs, and I've had CF cache turned off when testing, so I am not sure what has caused this.
Just updated to latest `:1` tag and it still works.

Thank you for the suggestion, even if I didn't have to use it in the end.

---

Just for the record, besides the compose above which remained unchanged, here's my traefik headers config:
```yaml
    middlewares-secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "same-origin"
        permissionsPolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
          server: ""
```
