### ISSUE TITLE
Add Monitor Descriptions to the Status Page

### ISSUE THREAD

**Issue by TritonB7** [louislam/uptime-kuma#3008]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Recently, the feature to add monitor model descriptions were added and these descriptions could be seen while hovering over the monitor in the dashboard. Can these same descriptions be displayed on the status page as well? With the option for hover and/or list the description underneath the monitor?

### ✔️ Solution

Our Uptime Kuma instance instance is only accessable by specific IP addresses so that my colleagues can view the status page. I do not want to give my colleagues access to the dashboard, where they could possible make unsupervised changes. Currently, the dashboard is the only way that I know of to view the descriptions. 

I think it would be a nice feature to have the monitor model description viewable on the status page as well.

- Create/edit a new monitor.
- In the monitor settings - Add toggle to enable allow description to be viewable on status page.
  For example:
  
        Monitor1 - Enable Status Page Description
        Monitor2 - Disable Status Page Description
        Monitor3 - Enable Status Page Description
        
- In the Status Page settings - Add global toggle to show Monitor Descriptions (e.g. if description is not empty/null)
   For example, after enabling this toggle:
   
         Monitor1 now displays a description underneath the monitor name on the Status Page.
         Monitor2 does not display description underneath the monitor name on the Status Page (the normal/current view).
         Monitor3 now displays a description underneath the monitor name on the Status Page.

![Monitor Settings](https://user-images.githubusercontent.com/31591982/229291949-1f81ed76-880b-4af1-b076-4c200348660f.png)
![Status Page](https://user-images.githubusercontent.com/31591982/229291952-4c301131-7000-4707-acf1-860fa99a8ea8.png)
![Status Page Settings](https://user-images.githubusercontent.com/31591982/229291958-18b95b07-e3a3-48bb-9c9c-a0a9f7358dfe.png)

### ❓ Alternatives

I am not aware of any current alternatives, if I could create multiple users with read permissions to the dashboard, the users would be able to see the descriptions as well, without having the descriptions displayed on the status page.

**Comment by Tiago8v** [comment]
Hello there, I had the same issue... and was able to bypass this "problem" by doing the following:

1. add tags (grey) on each monitor with the description text that I wanted to add
2. activate tags on status page
3. add the following CSS code on the status page

```
.tag-wrapper {
  background: none !important; /* Hides colored background */
  color: #666 !important; /* Greys out text */
}

.tag-wrapper:first-child{
  padding-left: 68px !important; /* Spaces first element to align with the monitor name */
}
```

While not perfect, it served my case! Hope it helps you too!


![status_example](https://github.com/louislam/uptime-kuma/assets/6554679/7aa8b4c6-0cfa-4268-8d65-bbecefa2108d)

**Comment by CommanderStorm** [comment]
<img src="https://media1.giphy.com/media/lXu72d4iKwqek/giphy.gif"/>

**Comment by Geczy** [comment]
i also came across the tag solution, here's my css

```css
.tag-text {
white-space: normal !important;
color: black;
}
.tag-wrapper {
background-color: transparent !important;
}
```

**Comment by hmnd** [comment]
To anyone looking here for an interim solution, here's a way to make the description appear as a tooltip:

1. Add your description to a monitor as a tag, as described above. Set the tag's color to pink and don't use pink for any other tags. Alternatively, change the `[style*="background-color: rgb(219, 39, 119)"]` to `:first-child` to always apply the CSS to the first tag shown on a monitor.
2. Add the following CSS to your status page:
```css
div.tag-wrapper[style*="background-color: rgb(219, 39, 119)"]::before {
    visibility: visible;
    content: "ⓘ";
    font-size: 1rem;
    margin-right: 0.25rem;
    background-color: #293245 !important;
    border-radius: 50rem !important;
    padding: 0.25rem 0.5rem;
    align-self: baseline;
    font-weight: bold;
}
div.tag-wrapper[style*="background-color: rgb(219, 39, 119)"] {
    visibility: hidden;
    transition: 0.2s 1s;
    max-width: 25rem;
    position: absolute;
    background-color: #293245 !important;
    padding-top: 0.5rem !important;
    padding-bottom: 0.5rem !important;
    border-radius: 0.5rem !important;
}
div.tag-wrapper[style*="background-color: rgb(219, 39, 119)"] .tag-text {
    white-space: normal !important;
}
div.tag-wrapper[style*="background-color: rgb(219, 39, 119)"]:where(
        :hover,
        :active
    ) {
    visibility: visible;
    transition-delay: 0s;
}
```

**Comment by Ionys320** [comment]
Hi,
I see #4612  is in draft, so I could work on my own solution if needed. 

Two questions :
1. Should we keep one description shared across the dashboard and the status page? Or instead, should we have a "technical" description and a "public" one? 
For this point, I think it would be easier to only have one, shared across the two parts of UK. If needed to have distinctive descriptions, we must define how the case "no public desc given but a technical one" is handled (`this.publicDescription ?? this.description` ?)

2. The "Show description" would be at the same place than the "Show URL" button (Option depending of each monitor)? Or would it be like tags (same option for all monitors)?

**Comment by recordcrash** [comment]
Here's a solution so long descriptions wrap:
```css
.tag-text {
width: 100% !important;
word-wrap: break-word !important;
white-space: wrap !important;
} 
.tag-wrapper {
background: none !important;
color: #666 !important;
width:100% !important;
}
div.extra-info > div:first-child {width:100% !important;}
```
