### ISSUE TITLE
Registering a monitor target

### ISSUE THREAD

**Issue by confiar** [louislam/uptime-kuma#3060]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

It would be very convenient if monitor registration is possible through API.

### ✔️ Solution

It would be nice if the API had required and optional parameters, and a method that could register the monitor target through http request was applied.

### ❓ Alternatives

I would like to be able to upload a csv file or register multiple monitor targets in a csv format on the web in bulk.

**Comment by jonnymccullagh** [comment]
I achieve this via Ansible with:
https://github.com/lucasheld/ansible-uptime-kuma
Ultimately I am defining each monitor in yaml e.g.
```
uptime_kuma_http_monitors:
  - name: "website1.com"
    url: "https://website1.com"
    tag: "prod"
    state: "present"
  - name: "website2.co.uk"
    url: "https://website2.co.uk"
    tag: "prod"
    state: "present"
  - name: "website3.co.uk"
    url: "https://website3.co.uk"
    tag: "dev"
    state: "present"
```
