### ISSUE TITLE
Best ways of avoiding temporary getaddrinfo EAI_AGAIN down notifications?

### ISSUE THREAD

**Issue by douglerner** [louislam/uptime-kuma#3123]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I did find this error mentioned at other sites, but couldn't find it here after a good faith search. I suspect it must have been raised before though.

 still just have a handful of monitors running at pikapod. Several of them today, checking completely different domains, sent down notifications with the error "getaddrinfo EAI_AGAIN" and then up a few minutes later. I think that's a domain lookup error, right?

My Uptime Robot monitors didn't report anything.

I'm guessing it's an issue with pikapod's DNS look or Internet connectivity or something like that, right?

Is there maybe a different setting that might reduce annoying messages like that, other than looking up by IP address rather than domain?

Thanks,

doug

### 🐻 Uptime-Kuma Version

1.21.12

### 💻 Operating System and Arch

Whatever pikapods uses

### 🌐 Browser

Whatever pikapods uses

**Comment by m3nu** [comment]
Hi Doug, you should **retry** a few times before marking your service offline. DNS timeouts can definitely happen if you monitor thousands or million times a day.

More here: https://stackoverflow.com/a/73581100

**Comment by douglerner** [comment]
I ended up adding a single retry. Pikapods said they also added extra DNS servers. I did get one instance of the DNS failure today though.

**Comment by douglerner** [comment]
I'm up to 3 retries now, but still get a lot of those EAI_AGAIN down messages every day across the half dozen or so servers I'm monitoring on PikaPods. I test every 300 seconds with a retry every 60 seconds for 3 times before a report is generated. It always comes back with an up message after a few minutes. But it happens much more frequently than the same monitors at Uptime Robot. I wonder what more I can do, or what the cause is. Thanks.

**Comment by m3nu** [comment]
So all good for the last 5 hours? Good to know. Will check again in a few hours.

**Comment by douglerner** [comment]
Well, I did sleep through the night with no notices! So you run Pikapods and just coincidentally check here? Or are you involved with both? Thanks.

**Comment by tpai** [comment]
Just saw the [Alpine 3.18](https://alpinelinux.org/posts/Alpine-3.18.0-released.html) released, it includes the musl libc upgrade which can fix the DNS resolve issue. Not sure it could help for the EAI_AGAIN error.

My way to fix the error is to specify DNS servers in docker-compose.yml file.
https://docs.docker.com/compose/compose-file/compose-file-v3/#dns

**Comment by m3nu** [comment]
I saw there is now a DNS cache option in Uptime Kuma. Did this help for this issue?

Regarding the specific DNS servers: Yes, at [PikaPods](https://www.pikapods.com/) we also add some popular public resolvers for all pods, but still not guaranteed to work 100% if one does many checks. To fully solve this, we would need a local DNS with a cache and retry settings. And optimize the settings a bit. Though for now I think this would be overkill and I hope it works well enough with the current setup.

**Comment by solracsf** [comment]
For the record, I completely solved those issues by installing `dnsmasq`.
`nscd` was causing many problems.

### docker.compose.yml
```
version: '3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - "3001:3001"
    dns:
      - 172.0.0.3
    networks:
      default:
        ipv4_address: 172.0.0.2

  dns:
    image: strm/dnsmasq
    container_name: dnsmasq
    restart: unless-stopped
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "5353:53/udp"
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 172.0.0.3

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.1/16
```
### dnsmasq.conf
```
no-resolv
log-queries
domain-needed
expand-hosts
bogus-priv
strict-order
server=1.1.1.1
server=8.8.8.8
cache-size=512
log-facility=-
```
