### ISSUE TITLE
getaddrinfo EAI_AGAIN  problem  not sure what to do 

### ISSUE THREAD

**Issue by regchanuk** [louislam/uptime-kuma#3371]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

getting this error while monitoring this specific site  cannot tell if its the site or  it just started 2 days ago 

getaddrinfo EAI_AGAIN filedogs.com
--
i have readded this several times but not really change anything tested on a second version too but seems to still happen  cant really see anything else i can do 

### 📝 Error Message(s) or Log

getaddrinfo EAI_AGAIN filedogs.com

seems to happen every 15 to 30 mins 

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

114.0.5735.199

### 🐋 Docker Version

20.10.17

### 🟩 NodeJS Version

0.0.0.0

**Comment by regchanuk** [comment]
good thing its not happening to any of my other sites tho

**Comment by louislam** [comment]
Maybe it is the domain name's dns issue. It means DNS query timeout.

1. Increase the TTL of your DNS A record to cache longer.
2. Migrate your DNS service to such as Cloudflare.

**Comment by solracsf** [comment]
I'm having the same issue `EAI_AGAIN`, no so frequently has 15m but some times per day (60 seconds check, DNS cache enabled or not, same result).

My DNS are already at Cloudfalre, and A and AAAA have both TTL of 1 day.

![image](https://github.com/louislam/uptime-kuma/assets/12234510/ffb0f1cb-a1ac-4118-9d9a-045718085fac)
![image](https://github.com/louislam/uptime-kuma/assets/12234510/6b17a20c-860e-4170-8baa-823e2867d8e8)

**Comment by slurdge** [comment]
Hello,

This problem is also occurring to me, and more and more with versions. I can go as far as 2022-11 but recently it went up.
I tried many things:

- Different DNS providers
  * Cloudflare (1.1.1.1)
  * Google (8.8.8.8)
  * Quad9
  * Control D
- It happens on almost all domains, but tend to happen on domains with shorter TTL. Increasing TTL does not solve the problem, just alleviate it
- In the end, I put dnsmasq as a caching server with a forced TTL of 1200s for all entries. This also alleviate but does not solve the problem.

With dnsmasq, I can see the query log in real time and I see that the queries are done "mostly" grouped. Is there a jitter on the monitors in order not to have all the queries at the same time ?

In the end, it becomes so prevalent that I think at least an option to retry on `EAI_AGAIN` should exists. I really love uptime kuma, I use it since first release and I have put more than 30 monitors, but I get 10+ false alerts per day now.

**Comment by louislam** [comment]
Try to study again, this article suggested `nscd`.

```
sudo apt-get install nscd
``` 

https://medium.com/@amirilovic/how-to-fix-node-dns-issues-5d4ec2e12e95

**Comment by slurdge** [comment]
@louislam Thanks, but would `nscd` be better than a caching `dnsmasq` ? Most (like 90%) of request are cached.
For example I have this in the logs:
```
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted> <CNAME>
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted>
uptime-kuma-dns-1  | dnsmasq[42]: query[A] <redacted> from 172.16.238.2
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted> <CNAME>
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted>
uptime-kuma-dns-1  | dnsmasq[42]: query[A] google.com from 172.16.238.2
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted>
uptime-kuma-dns-1  | dnsmasq[42]: query[A] www.google.com from 172.16.238.2
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted> 
uptime-kuma-dns-1  | dnsmasq[42]: query[A] <redacted> from 172.16.238.2
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted>
uptime-kuma-dns-1  | dnsmasq[42]: query[A] <redacted> from 172.16.238.2
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted> 
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted> 
uptime-kuma-dns-1  | dnsmasq[42]: query[A] <redacted> from 172.16.238.2
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted>
uptime-kuma-dns-1  | dnsmasq[42]: query[A] <redacted> from 172.16.238.2
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted>
uptime-kuma-dns-1  | dnsmasq[42]: query[A] <redacted> from 172.16.238.2
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted>
uptime-kuma-dns-1  | dnsmasq[42]: query[A] <redacted> from 172.16.238.2
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted> <CNAME>
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted>
uptime-kuma-dns-1  | dnsmasq[42]: query[A] <redacted> from 172.16.238.2
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted> <CNAME>
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted> 
uptime-kuma-dns-1  | dnsmasq[42]: query[A] <redacted> from 172.16.238.2
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted> <CNAME>
uptime-kuma-dns-1  | dnsmasq[42]: cached <redacted>
```

My docker compose looks like this:
```
version: '3.3'

services:
  dns:
    image: drpsychick/dnsmasq
    restart: always
    env_file: dnsmasq.env
    expose:
      - '53/udp'
      - '53/tcp'
    cap_add:
      - NET_ADMIN
    command: ["-k", "--log-facility=-", "--cache-size=1000", "--no-dhcp-interface=", "--min-cache-ttl=1200", "--log-queries"]
    networks:
      network:
        ipv4_address: 172.16.238.3
  uptime-kuma:
    image: louislam/uptime-kuma:1
    depends_on: [dns]
    container_name: uptime-kuma
    volumes:
      - /opt/uptime-kuma/data:/app/data
    dns:
      - "172.16.238.3"
    networks:
      network:
        ipv4_address: 172.16.238.2
    ports:
      - 3001:3001
    restart: always
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
```

Another thing is that someone could/would want a full docker solution without relying on the host having `ncdu`.

Nevertheless I will install it and see if it changes something.

**Comment by louislam** [comment]
> Thanks, but would nscd be better than a caching dnsmasq ?

I can't tell, because I can never reproduce this issue, but `EAI_AGAIN` is indeed existing for a long time here.

> Another thing is that someone could/would want a full docker solution without relying on the host having ncdu.

If it is better, I think `nscd` could be embedded into the Uptime Kuma image.

> Nevertheless I will install it and see if it changes something.

Thanks, don't forget to check the stats with `nscd -q`.

**Comment by louislam** [comment]
The article also suggested that it should increase UV_THREADPOOL_SIZE to 128 (default value is 4).

If nscd is not working, it is also worth to try, it should be a environment variable that pass to uptime-kuma's container.

**Comment by slurdge** [comment]
So, `nscd` works for me.
I'm not trying `UV_THREADPOOL_SIZE =128` in env.

**Comment by louislam** [comment]
> So, `nscd` works for me.

Interesting, I read the article again, it said that `nscd` actually works with `getaddrinfo` directly. Maybe that is the reason why it is better than `dnsmasq`.


https://jameshfisher.com/2018/02/03/what-does-getaddrinfo-do/
> At least, that’s what I thought. As it turns out, the source of nscd is buried in glibc. (Despite this program not being part of libc!) The protocol for nscd is not specified, and there are virtually no alternative implementations! nscd is not part of the C standard library.

**Comment by solracsf** [comment]
All my monitors just went down a few minutes ago with EAI_AGAIN problem. Up again, all of them, 20 minutes later!!

This is causing more trouble than it solves... Cc @louislam

**Comment by solracsf** [comment]
For the record, I completely solved those issues by installing `dnsmasq`.
`nscd` was causing many problems.

### docker.compose.yml
```
version: '3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - "3001:3001"
    dns:
      - 172.0.0.3
    networks:
      default:
        ipv4_address: 172.0.0.2

  dns:
    image: strm/dnsmasq
    container_name: dnsmasq
    restart: unless-stopped
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "5353:53/udp"
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 172.0.0.3

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.1/16
```
### dnsmasq.conf
```
no-resolv
log-queries
domain-needed
expand-hosts
bogus-priv
strict-order
server=1.1.1.1
server=8.8.8.8
cache-size=512
log-facility=-
```
