### ISSUE TITLE
Automatic Configuration from Git-Versioned .yml on Container Creation

### ISSUE THREAD

**Issue by marco-carvalho** [louislam/uptime-kuma#3455]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

When deploying Uptime Kuma as a container, administrators often need to configure all monitors manually after the initial setup. This manual configuration can become quite tedious, especially when deploying multiple instances or recovering from backups. The ability to automatically read configurations from a `.yml` file upon container initialization would significantly streamline this process.

### ✔️ Solution

I'd like Uptime Kuma to have the ability to automatically read a `.yml` file located in the same folder as the container during its creation. This file should contain all the configurations for the monitors, including URLs, monitoring intervals, notification settings, etc. By doing so, when the container is initialized, Uptime Kuma should automatically set up the monitors as per the `.yml` file, eliminating the need for manual configuration.

**Proposed format**:
```yaml
monitors:
  - name: "Monitor 1"
    url: "http://example1.com"
    interval: 5
    type: "http"
    ...
  - name: "Monitor 2"
    url: "http://example2.com"
    interval: 10
    type: "tcp"
    ...
```
