### ISSUE TITLE
Have a JSON Endpoint for polling of metrics (Home Assistant)

### ISSUE THREAD

**Issue by iotemylabs** [louislam/uptime-kuma#346]
Hi!

I really love Uptime-Kuma, I just deployed this on my home and office servers!

I wanted to get metrics like the Prometheus endpoint as a JSON endpoint so I can port info direct to home assistant :)

Thank you!

**Comment by louislam** [comment]
Duplicate of #118

**Comment by hendrikma** [comment]
I came a long with an other solution to this topic since there are only Notifications available when there is some service down but not for monitoring the status:

```
sensor:
  - platform: command_line
    name: Uptime Kuma Test
    command: curl -s -u <YOUR_USER>:<YOUR_PASSWORD> http://<YOUR_IP>:3001/metrics | grep -Poi '^monitor_response_time{.*?} \d+$'
    unit_of_measurement: "ms"
    value_template: >-
      {{ value | regex_findall_index(find="monitor_hostname=\"<ESCAPED_HOSTNAME>\".*} (\d*)", index=0, ignorecase=False) }}
```

Thats for getting the Response-Time for a Hostname. You have to escape the hostname correctly like so
my.hostname.to.monitor > my\.hostname\.to\.monitor

Have fun with it ;)
