### ISSUE TITLE
ntfy notification is the actual json string

### ISSUE THREAD

**Issue by stock90975** [louislam/uptime-kuma#3476]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I'm using ntfy to send alerts from uptime-kuma. \
The notification received in the ntfy android app is the actual JSON string ie.
{"topic":"Alert", "title": "Alert [Uptime-Kuma]", "message": "Ntfy alert Testing", "priority":3, "tags":["test_tube"]}

### 👟 Reproduction steps

eg. setup notification > test
or
actual notification from service down, etc.

### 👀 Expected behavior

proper ntfy notification with title, priority, etc.

### 😓 Actual Behavior

seeing JSON string of the notification

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Not applicable

**Comment by CommanderStorm** [comment]
As far as I am reading https://docs.ntfy.sh/publish/#publish-as-json we are using it correctly.
Here is the code we use:

https://github.com/louislam/uptime-kuma/blob/a0203372ce26b5d7aafd0af53a5c45a183eceecf/server/notification-providers/ntfy.js#L22-L67

Could you give further detais on your deployment method? Are you self-hosting? If yes, what version are you running?

**Comment by stock90975** [comment]
running self hosted docker, docker-compose.yaml is:
```
services:

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - "/projects/uptime-kuma/data:/app/data"
    ports:
      - "3001:3001"
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
```
command to start is:
```
docker-compose up --detach --force-recreate
```
uptime kuma version is 1.22.1 (from settings>about)

android app receiving is ntfy (version is ntfy 1.16.0 (play) 
android is stock, non rooted

ntfy channel is a public channel (ntfy.sh/...)

The android ntfy app is receiving other notifications formatted correctly from other apps.

Everything is out of the box, as far as I can tell. Thanks!

**Comment by CommanderStorm** [comment]
Cannot reproduce:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/1d37a8d9-881a-4f99-a77c-2879af947e27)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/5290011c-5699-418c-be18-c0baefbed3b9)

**Comment by CommanderStorm** [comment]
Also tested If maybe there is some weirdness with more than just the testing => Nope
![image](https://github.com/louislam/uptime-kuma/assets/26258709/b1bdb0eb-1c25-45cc-a93b-1a09dbde7a6e)

Currently, I could not replicate this issue.
Can you provide us a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by stock90975** [comment]
As above:
docker-compose.yaml
```
services:

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - "/projects/uptime-kuma/data:/app/data"
    ports:
      - "3001:3001"
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"

```
```
docker-compose up --detach --force-recreate
```
![Screenshot from 2023-07-26 12-06-41](https://github.com/louislam/uptime-kuma/assets/54917811/dd58bd42-a297-4a89-bb5b-4f1a96dcdf53)

![Screenshot from 2023-07-26 12-06-57](https://github.com/louislam/uptime-kuma/assets/54917811/b3af8c88-015e-4597-a222-f055b48812d8)
