### ISSUE TITLE
FR: Config File

### ISSUE THREAD

**Issue by userbradley** [louislam/uptime-kuma#3578]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I work a lot with _configuration as code_ and was surprised to see that this (amazing) tool was missing it.

I'd like to see a yaml file that users can either mount to the container on run time, or users can upload in the UI to configure stuff like authentication, reverse proxies etc etc

### ✔️ Solution

Below is a rough draft of what a monitor and group could look like

```yaml
group:
  - name: "External Services"
    heartBeatInterval: 60
    retries: 1
    advanced:
      upsideDown: true
    tags:
      - test
      - test1
monitor:
  - name: "breadNET"
    group: "External Services"
    description: -|
      breadNEt External site
    type: http
    url: "https://breadnet.co.uk"
    heartBeatInternal: 20
    advanced:
      certExpiryNotification: true
      upsideDown: true
```

### ❓ Alternatives

Nothing, I am happy to use this as is, but would be nice to configure this through helm charts, or as code

### 📝 Additional Context

Keep doing what you're doing, this is awesome!
