### ISSUE TITLE
Setting up Docker host with socket raises "Invalid URL" error

### ISSUE THREAD

**Issue by davidwinter** [louislam/uptime-kuma#3605]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When trying to add a Docker Host via socket, and clicking Test, it throws an error "Invalid URL".

<img width="977" alt="image" src="https://github.com/louislam/uptime-kuma/assets/9681/9308ce50-ea50-425c-a6c7-b3570a50a6a7">

### 👟 Reproduction steps

Using the following `compose.yml` file:

```yml
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: always
```

And then running uptime-kuma with:

```sh
sudo docker compose up -d
```

Running on Raspberry PI OS Lite (64-Bit)

### 👀 Expected behavior

For the "Test" action to succeed and no error message to be displayed.

### 😓 Actual Behavior

It throws an error "Invalid URL" even though I've selected "Socket" as the type and a file path.

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

Raspberry PI OS Lite (64-bit) / Debian Bullseye 11

### 🌐 Browser

Firefox 116.0.2 (64-bit)

### 🐋 Docker Version

Docker version 24.0.5, build ced0996
