### ISSUE TITLE
Edit CSS of Status pages

### ISSUE THREAD

**Issue by gsg-git** [louislam/uptime-kuma#3657]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello!

I set a Image in the background and want to set the boxes a transparence efect:

What i found are two places whre the colour ist set in the CSS files - i use the dark theme.

src/assets/vars.scss and src/pages/StatusPage.vue i want to change the colour #0d1117 to #0d1117d1

I used the Web tools in FF and Github search to find the values where to change, but the fields stay black - when i set it in the view unter custom css like the wallpaper the change was just temporary.

I clear after every change the brower cache and try additionaolly via Opera.

.dark .shadow-box[data-v-3042fc32] {

background-color: #0d1117d1;

}

The Uptime Kuma is installed in Docker for windows and the newest version.

Thank you in advance for you tips!
![grafik](https://github.com/louislam/uptime-kuma/assets/92863111/cd83291b-4ce2-48d8-bb0e-4d8655624bee)
how i want the Transparency

![grafik](https://github.com/louislam/uptime-kuma/assets/92863111/aa4c16ac-5c3c-4cff-b48e-5865b651de82)
How it is now

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

Docker for Windows

### 🌐 Browser

Firefox,Edge,Opera

### 🐋 Docker Version

v4.22.0

**Comment by imkuroneko** [comment]
Try
```css
.dark .shadow-box[data-v-3042fc32] {
    background-color: rgba(13, 17, 23, 0.4);
}
```
instead of
```css
.dark .shadow-box[data-v-3042fc32] {
    background-color: #0d1117d1;
}
```
