### ISSUE TITLE
prometheus issue : context deadline exceeded

### ISSUE THREAD

**Issue by Spleenftw** [louislam/uptime-kuma#3742]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

```
My prometheus is supposed to scrap from my uptime-kuma with this configuration : 

 interlope@Portainer:~/docker/prometheus$ cat prometheus.yml
# my global config
global:
  scrape_interval: 5m
  evaluation_interval: 1m

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape: Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'uptime'
    scrape_interval: 30s
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: ['10.100.22.42:3001']
    basic_auth: # Only needed if authentication is enabled (default)
      username: xx
      password: xx
 ```

   But i kinda dont get it working

### 📝 Error Message(s) or Log

```
Get "http://10.100.22.42:3001/metrics": context deadline exceeded
```

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

debian 11

### 🌐 Browser

braves

### 🐋 Docker Version

20.10.5
