### ISSUE TITLE
PING and HTTP works, but DNS fails

### ISSUE THREAD

**Issue by ElastiCourse** [louislam/uptime-kuma#3831]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I had this issue for a while, and I checked the similar discussions regarding this issue but I couldn't get the issue resolved.

I have Uptime Kuma installed via Docker. It's placed in the default bridged network. I have another container running Pi-Hole DNS server. It's placed in another bridged network **pc_default** (docker compose based)

Uptime Kuma can ping the host machine itself with no issue. It can also access the pihole container via HTTP call with no issue. However it can not do a proper DNS query. I have no plan to connect docker sock or monitor Docker as a whole. I just need to monitor DNS. I'm wondering why can't DNS be reached from another container?
![31-Uptime Kuma](https://github.com/louislam/uptime-kuma/assets/71233127/1fa07aec-38cf-424b-b67f-c2b6ef840ff6)
![30-Uptime Kuma](https://github.com/louislam/uptime-kuma/assets/71233127/b924c214-80f7-432d-b526-d3fe3f39852a)
![28-Uptime Kuma](https://github.com/louislam/uptime-kuma/assets/71233127/51ce2a55-6d64-428f-9c7e-e87cbbd3a70c)
![27-Uptime Kuma](https://github.com/louislam/uptime-kuma/assets/71233127/c3e5ed74-e86e-44cd-af65-ca1d73dc33e8)
![26-Uptime Kuma](https://github.com/louislam/uptime-kuma/assets/71233127/94bc5eab-cbf1-419e-9ac9-8e2f9afae238)

I believe the container --link command is now legacy, so I decided to try 
```docker network connect bridge pihole```
That didn't work at all

Next, I tried to deploy uptime kuma in the same network as pihole **pc_default**
`docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --network=pc_default --name uptime-kuma louislam/uptime-kuma`
That didn't work either

HOWEVER, with Uptime kuma still in the **pc_default**, and by changing the monitor resolver IP from HOST machine's IP to container internal IP (from inspect command it's 172.18.0.2, it finally WORKED.

It's not very ideal to have to inspect containers and check their IPs individually and also have monitors for the same service divided into multiple IPs. 

Any ideas how to reach containers via DNS on the same machina?

Thanks to all devs for this great app.

### 📝 Error Message(s) or Log

queryA ETIMEOUT google.com

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Ubuntu LM

### 🌐 Browser

Chrome Latest

### 🐋 Docker Version

Docker version 24.0.5

**Comment by CallumAlbert** [comment]
Which Uptima Kuma container are you using? If you're using the Alpine one it's possible it's an alpine related issue.

**Comment by ElastiCourse** [comment]
> Which Uptima Kuma container are you using? If you're using the Alpine one it's possible it's an alpine related issue.

I'm using the latest tag for the version. Based on digest `273cde543a31` looks like this is the debian version.

**Comment by gzfrozen** [comment]
@ElastiCourse 
Does this solve the problem?
https://stackoverflow.com/questions/64007727/docker-compose-internal-dns-server-127-0-0-11-connection-refused

I had a similar issue and I just fixed the issue with above method.

**Comment by ElastiCourse** [comment]
> @ElastiCourse Does this solve the problem? https://stackoverflow.com/questions/64007727/docker-compose-internal-dns-server-127-0-0-11-connection-refused
> 
> I had a similar issue and I just fixed the issue with above method.

WOW you just made my day go green. Thanks

![2023-10-15 01_30_11-- Brave](https://github.com/louislam/uptime-kuma/assets/71233127/b9dfaf01-03e1-4abf-8ce0-0b6d975b3708)

Full code if someone else stumbles across this github issue **docker-compose.yaml**

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - 192.168.150.72:53:53/tcp
      - 192.168.150.72:53:53/udp
      - 192.168.150.72:8080:80/tcp
    environment:
      TZ: 'America/New_York'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    restart: unless-stopped
```
