### ISSUE TITLE
SQLITE_CORRUPT

### ISSUE THREAD

**Issue by modem7** [louislam/uptime-kuma#3958]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Heya, 

I've recently recreated a VPS, and restored my backup. 

Compose, .env, paths, permissions, users etc are all exactly the same.

Currently getting a SQLITE_CORRUPT error. 

The only x-factor is that originally the environment was x86, and now it's ARM.

### 📝 Error Message(s) or Log

[error.log](https://github.com/louislam/uptime-kuma/files/13197104/error.log)

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Ubuntu 22.04 ARM

### 🌐 Browser

Chrome

### 🐋 Docker Version

24.0.7

**Comment by modem7** [comment]
Compose config:

```yaml
 ##############
 #Uptime-Kuma##
 ##############

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: Uptime-Kuma
    hostname: UptimeKuma
    environment:
#      UPTIME_KUMA_CLOUDFLARED_TOKEN: $CF_TUN_TOKEN
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      - autoheal=true
    volumes:
      - $USERDIR/UptimeKuma:/app/data
    network_mode: "host"
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: always
    depends_on:
      - cloudflared
```
