### ISSUE TITLE
Healthcheck in Docker file doesn't work? Trying to make my caddy service to wait for uptime-kuma "healthy" status!

### ISSUE THREAD

**Issue by gremo** [louislam/uptime-kuma#4098]
The Docker file seems to have the [HEALTHCHECK](https://github.com/louislam/uptime-kuma/blob/67250d6302f42bd9ccb8ac83350b1bbcc71b4086/docker/dockerfile#L41) istruction. 

In my Compose file, when I try to make my `caddy` service depends on the status of `uptime-kuma `service, it won't work: `caddy` is waiting forever and it won't start.

Here is my `compose.yaml`:

```yaml
services:
    caddy:
        image: lucaslorentz/caddy-docker-proxy
        container_name: ${COMPOSE_PROJECT_NAME}-caddy
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        volumes:
            - caddy_data:/data
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
        depends_on:
            uptime-kuma:
                condition: service_healthy

    uptime-kuma:
        image: louislam/uptime-kuma
        container_name: ${COMPOSE_PROJECT_NAME}-uptime-kuma
        volumes:
            - uptime-kuma:/app/data
        restart: unless-stopped
        labels:
            caddy: ${DOMAIN:-localhost}
            caddy.reverse_proxy: "{{upstreams 3001}}"

volumes:
    caddy_data:
    uptime-kuma:

```

It works only relaying on the started condition:

```yaml
services:
    caddy:
        # ...
        depends_on:
            - uptime-kuma
```

Any help is much appreciated!
