### ISSUE TITLE
Connecting to Docker via TLS fails when configuring docker hosts but not when manually connectiong with openssl

### ISSUE THREAD

**Issue by UmbraTenebrae** [louislam/uptime-kuma#4108]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have configured a remote docker server on my network to accept TLS connections so I can monitor the containers directly.  I have pored over the other issues on this project and have implemented all of the suggested fixes.  I have raised this as a new issue as the behavior does not correspond with the previous similar issues and is not resolved by their suggested fixes.  What appears to be happening is that uptime-kuma is not presenting the certificate properly when connecting.  If I drop into the container and connect via openssl manually, specifiyng the cert, CA, and key files in their in-container locations, it accepts the connection.  When I try to use the configured host in the GUI, it fails and throws a bad cert error (ssl alert 42).

docker compose: 

```
version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    environment: 
     NODE_EXTRA_CA_CERTS: '/etc/ca.pem'
     UPTIME_KUMA_SSL_CERT: '/etc/cert.pem'
     UPTIME_KUMA_SSL_KEY: '/etc/key.pem'
    volumes:
      - uptime-kuma:/app/data
      - /ssl:/etc
    ports:
      - "3001:3001"  # <Host Port>:<Container Port>
    restart: always

volumes:
  uptime-kuma:
```

Running `openssl s_client -connect https://<serverip>:2376 -cert /etc/cert.pem -key /etc/key.pem -CAfile /etc/ca.pem` from within the container successfully opens a connection and the certificates all jive.

### 👟 Reproduction steps

1. configure a directory to mount a volume against, in this case i am using /ssl to mount the container's /etc against
2. put the certificates in this directory
3. configure the appropriate environment variables:
```
 NODE_EXTRA_CA_CERTS: '/etc/ca.pem'
     UPTIME_KUMA_SSL_CERT: '/etc/cert.pem'
     UPTIME_KUMA_SSL_KEY: '/etc/key.pem'
    volumes:
      - uptime-kuma:/app/data
      - /ssl:/etc
```
4. restart/recreate the container for shiggles and/or good measure
5. configure a docker host using the TCP/HTTPS method, pointing at `http://<serverIP>:2376` and click test
6. observe the failure

### 👀 Expected behavior

I expect the behavior of node.js utilizing the specified certificates to mirror the behavior of a manual openssl cli connection.

### 😓 Actual Behavior

Actual behavior is uptime-kuma seems unable to properly grab or utilize the certificates, or is using the wrong one.  log output:

```
 | Interval: 20 seconds | Type: docker | Down Count: 0 | Resend Interval: 0
 | Max retries: 1 | Retry: 1 | Retry Interval: 20 seconds | Type: docker
2023-11-26T01:11:32-05:00 [MONITOR] WARN: Monitor #12 '<editedContainerName>': Pending: C027E047787F0000:error:0A000412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 42
2023-11-26T01:11:52-05:00 [MONITOR] WARN: Monitor #12 '<editedContainerName>': Failing: C027E047787F0000:error:0A000412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 42
```

### 🐻 Uptime-Kuma Version

1.23.7

### 💻 Operating System and Arch

ubuntu 22.0.4.3 LTS

### 🌐 Browser

Firefox 120

### 🐋 Docker Version

Remote server - 20.10.23, Local Server - 24.0.5
