### ISSUE TITLE
CSS + HTML[!] in Status Page

### ISSUE THREAD

**Issue by XHyperDEVX** [louislam/uptime-kuma#4278]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

I would like to make my status pages a bit prettier and wanted to use the CSS interface for this. Since I am unfortunately not able to write good CSS code myself, I searched the internet. However, I can ONLY find css backgrounds that need special html code. So objects that must be present in the html page for the css code to work. But in Uptime Kuma I only have the possibility to enter CSS code.

How should I do this now?

### 🐻 Uptime-Kuma Version

newest stable docker image

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Edge

### 🐋 Docker Version

Docker version 20.10.24

**Comment by CommanderStorm** [comment]
First of all, I don't think adding other elements is nessesary.
What are you trying to achive concretely?

Adding custom html is tracked in https://github.com/louislam/uptime-kuma/issues/2818

See https://github.com/louislam/uptime-kuma/wiki/Status-Page#custom-subdirectory--custom-html-on-status-pages for a solution that would not require said feature

**Comment by XHyperDEVX** [comment]
@CommanderStorm 
I just want to have a calm background for my status page. Like this one:
https://codepen.io/alvarotrigo/pen/GRvYNax

**Comment by CommanderStorm** [comment]
The example you provided does not work whatsoever with the current theme, but sure.. whatever floats your boat:

![image](https://github.com/louislam/uptime-kuma/assets/26258709/4ab6f18a-d4b9-4c33-b728-15e63ca5e376)

To get this done, you need to the footer:

<details><summary>html for the footer</summary>
<p>


```html
<ul class="circles">
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
</ul>
```


</p>
</details> 


The only modification to the css are:
- our root element is `body`, not `.area`
- because the `z-index` of the circles shoud be not on top
  <details><summary>(the <code>z-index</code> is there to avoid the site not being clickable)</summary>
  <p>
  
  
  ![image](https://github.com/louislam/uptime-kuma/assets/26258709/7adc15f1-76c0-46c1-baca-386583d5fad6)
  
  </p>
  </details> 

<details><summary>Here is the css-code</summary>
<p>

```css
@import url('https://fonts.googleapis.com/css?family=Exo:400,700');

body {
    font-family: 'Exo', sans-serif !important;;
    background: #4e54c8 !important;;  
    background: -webkit-linear-gradient(to left, #8f94fb, #4e54c8) !important;
}

.circles{
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    overflow: hidden;
}

.circles li{
    z-index: -1;
    position: absolute;
    display: block;
    list-style: none;
    width: 20px;
    height: 20px;
    background: rgba(255, 255, 255, 0.2);
    animation: animate 25s linear infinite;
    bottom: -150px;
    
}

.circles li:nth-child(1){
    left: 25%;
    width: 80px;
    height: 80px;
    animation-delay: 0s;
}


.circles li:nth-child(2){
    left: 10%;
    width: 20px;
    height: 20px;
    animation-delay: 2s;
    animation-duration: 12s;
}

.circles li:nth-child(3){
    left: 70%;
    width: 20px;
    height: 20px;
    animation-delay: 4s;
}

.circles li:nth-child(4){
    left: 40%;
    width: 60px;
    height: 60px;
    animation-delay: 0s;
    animation-duration: 18s;
}

.circles li:nth-child(5){
    left: 65%;
    width: 20px;
    height: 20px;
    animation-delay: 0s;
}

.circles li:nth-child(6){
    left: 75%;
    width: 110px;
    height: 110px;
    animation-delay: 3s;
}

.circles li:nth-child(7){
    left: 35%;
    width: 150px;
    height: 150px;
    animation-delay: 7s;
}

.circles li:nth-child(8){
    left: 50%;
    width: 25px;
    height: 25px;
    animation-delay: 15s;
    animation-duration: 45s;
}

.circles li:nth-child(9){
    left: 20%;
    width: 15px;
    height: 15px;
    animation-delay: 2s;
    animation-duration: 35s;
}

.circles li:nth-child(10){
    left: 85%;
    width: 150px;
    height: 150px;
    animation-delay: 0s;
    animation-duration: 11s;
}


@keyframes animate {
    0%{
        transform: translateY(0) rotate(0deg);
        opacity: 1;
        border-radius: 0;
    }

    100%{
        transform: translateY(-1000px) rotate(720deg);
        opacity: 0;
        border-radius: 50%;
    }
}
```

</p>
</details>

**Comment by XHyperDEVX** [comment]
@CommanderStorm 
yes, i realize that, but where does the footer part have to go?

**Comment by CommanderStorm** [comment]
Into the `Footer Text` field 

![image](https://github.com/louislam/uptime-kuma/assets/26258709/1b36a430-26bd-4abd-a6de-2841957f24e8)

**Comment by XHyperDEVX** [comment]
Thank you! My status page is scrollable, do you happen to know how to start the rectangles at the bottom of the page?

**Comment by CommanderStorm** [comment]
The reason the css is limited to the screen size is that `.circles` sets `height: 100%`. In the context of `position: absolute; top: 0` is aproximately the screen size (not accountign for mobile screensizes).

If you want this larger, you need to know how large as far as I know. The only thing that comes to mind is reusing the already existing elements instead of using 
```css
.circles {
  height: 100%
  position: absolute;
  top: 0
}
```

=> either you fade out at the bottom or make `.circles` way larger (to not have to adjust it every time you add new monitors ^^) with more boxes moving around.
