### ISSUE TITLE
Uptime Kuma Alert

### ISSUE THREAD

**Issue by Iranus** [louislam/uptime-kuma#4343]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Good morning,

I hope someone can guide me in my problem, let me explain:

I have been using Uptima Kuma as a docker for almost a year now
I often update the container, at this level - no problem.
The problem comes from the Uptima Kuma web interface in terms of notifications.

When I receive alerts on the interface that a probe is available again, it is displayed in green at the bottom right then it disappears after a few seconds, however the notifications are in red to say that my probe is not not available, remains constantly until I delete it myself via the touch screen.
Is this a configuration issue? From my iPad?

![uptima_kuma](https://github.com/louislam/uptime-kuma/assets/3825124/6937a64f-cdbd-4758-9c3f-364287c91603)

Thanks for your help

### 📝 Error Message(s) or Log

My docker compose

```yaml
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
``` 

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian 6.1.37-1 

### 🌐 Browser

iOS 15.8

### 🐋 Docker Version

Docker : 20.10.24+dfsg1 / Portainer 2.18.4
