### ISSUE TITLE
Define user when using docker compose

### ISSUE THREAD

**Issue by Feriman22** [louislam/uptime-kuma#4377]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'd like to run Uptime Kuma with a different user in Docker, because currently it's running as root.
How can I define it here?

Example:

```
    environment:
      - USER_ID=1006
      - GROUP_ID=996
```

Thanks!

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian 10.12

### 🌐 Browser

Google Chrome 120

**Comment by CommanderStorm** [comment]
See https://github.com/louislam/uptime-kuma/wiki/Environment-Variables#docker-specific-environment-variables
You could use the standard `PUID`/`PGID`. I have not tested if they work.

`v2` will come with full support of running as another user via the `-rootless` tags. See https://github.com/louislam/uptime-kuma/pull/4052 for further context.
See https://github.com/louislam/uptime-kuma/pull/4171 for what bugfixes still need to happen until a first beta can be issued.

**Comment by Feriman22** [comment]
Hmm, that's strange... The document says that the default PUID and GUID are 1000, but when I set these values:

```
    environment:
      - PUID=1000
      - PGID=1000
```

in a docker compose, the Uptime Kuma cannot check the container status. Any idea why?

![image](https://github.com/louislam/uptime-kuma/assets/22872515/0fb68a47-bc13-48ca-a9fa-7a213a5dab71)

**Comment by Feriman22** [comment]
You can find my docker compose below. I have added it as read only, due to the checking doesn't require a write permission.

`srw-rw---- 1 root docker 0 Jan 14 12:14 /var/run/docker.sock`

The user with PIUD `1000` is part of the `docker` group, so it has an access to it.

```
version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:alpine
    container_name: uptime-kuma
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/Docker/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3001:3001
    restart: always
    network_mode: bridge
    cpus: 0.5
    mem_limit: 400M
```
