### ISSUE TITLE
Nightly docker image broken

### ISSUE THREAD

**Issue by rg9400** [louislam/uptime-kuma#453]
**Describe the bug**
My container auto-updated, and the latest image is broken and simply will not start

**To Reproduce**

1. Use below compose, start container. Might need an existing DB

```yaml
  uptime-kuma:
    image: louislam/uptime-kuma:nightly
    container_name: uptime-kuma
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFDIR}/uptime-kuma:/app/data
    ports:
      - 3001:3001
    hostname: ${HOSTNAME}
    logging: *default-logging
    labels: *default-labels
    restart: unless-stopped
 ```

**Expected behavior**
Container should start

**Info**
Uptime Kuma Version: Commit 2820118ebad2bb6c3af0f560409f21cec039c523
Using Docker?: Yes
Docker Version: Docker version 20.10.8, build 3967b7d
OS: Docker via WSL2

**Error Log**
```
==> Performing startup jobs and maintenance tasks

==> Starting application with user 1000 group 1001

Welcome to Uptime Kuma

Node Env: production

Importing Node libraries

Importing 3rd-party libraries

Importing this project modules

Prepare Notification Providers

Version: 1.6.0-nightly

Creating express and socket.io instance

Server Type: HTTP

Data Dir: ./data/

Connecting to Database

Knex: run

$ npm install sqlite3 --save

/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /app/node_modules/@louislam/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node)

Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /app/node_modules/@louislam/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node)

    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)

    at Module.load (internal/modules/cjs/loader.js:937:32)

    at Function.Module._load (internal/modules/cjs/loader.js:778:12)

    at Module.require (internal/modules/cjs/loader.js:961:19)

    at require (internal/modules/cjs/helpers.js:92:18)

    at Object.<anonymous> (/app/node_modules/@louislam/sqlite3/lib/sqlite3-binding.js:4:15)

    at Module._compile (internal/modules/cjs/loader.js:1072:14)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

    at Module.load (internal/modules/cjs/loader.js:937:32)

    at Function.Module._load (internal/modules/cjs/loader.js:778:12)

Trace: Error: Knex: run

$ npm install sqlite3 --save

/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /app/node_modules/@louislam/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node)

    at Client_SQLite3.initializeDriver (/app/node_modules/knex/lib/client.js:182:13)

    at new Client (/app/node_modules/knex/lib/client.js:71:12)

    at new Client_SQLite3 (/app/node_modules/knex/lib/dialects/sqlite3/index.js:20:5)

    at knex (/app/node_modules/knex/lib/knex-builder/Knex.js:12:28)

    at Function.connect (/app/server/database.js:62:30)

    at initDatabase (/app/server/server.js:1213:20)

    at /app/server/server.js:128:11

    at Object.<anonymous> (/app/server/server.js:1130:3)

    at Module._compile (internal/modules/cjs/loader.js:1072:14)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

    at process.<anonymous> (/app/server/server.js:1326:13)

    at process.emit (events.js:400:28)

    at processPromiseRejections (internal/process/promises.js:245:33)

    at processTicksAndRejections (internal/process/task_queues.js:96:32)

If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues

```
