### ISSUE TITLE
Docker image doesn't start on Debian 10 / Portainer

### ISSUE THREAD

**Issue by te-deum** [louislam/uptime-kuma#4602]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I use Docker compose to try to run Kuma with Docker Compose.
Here is my Docker compose yml (from this repo) :
```
version: '3.8'

services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    volumes:
      #- ./data:/app/data
      - ./server:/app/server
      - ./db:/app/db
    ports:
      - "3001:3001"  # <Host Port>:<Container Port>
      - "3307:3306"
```

### 📝 Error Message(s) or Log

```
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
node:internal/modules/cjs/loader:1137
  throw err;
  ^
Error: Cannot find module '/app/server/server.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Node.js v18.19.0

When I connect to docker image, I can see /app/server/server.js file in the container.
### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Debian 10

### 🌐 Browser

Firefox 123

### 🖥️ Deployment Environment

- Runtime: Docker 25.0.5 / nodejs 18.19.0
- Database: sqlite/embedded ?(never started)
- Filesystem used to store the database on: ext4 (72GB available)
- number of monitors: 0 (never started)
