### ISSUE TITLE
Traefik 2.11.1 & 3.0.0-rc4 break websocket connections

### ISSUE THREAD

**Issue by thielj** [louislam/uptime-kuma#4669]
See https://github.com/traefik/traefik/issues/10598

Fix: roll-back or wait for the update

Workaround: add this to your entrypoint in eg. traefikyml (static config):

```
    transport:
      respondingTimeouts:
        tcp:
          lingeringTimeout: 180
```
