### ISSUE TITLE
Uptime-kuma + Traefik issue stuck on look to connect to socket server

### ISSUE THREAD

**Issue by arminmacx** [louislam/uptime-kuma#4672]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I recently try to add uptime to my homelab but when i try that with traefik as my reverse proxy, uptime dashboard refresh and gave error that it cannot connect to socker server. I laready read the uptime dock about how to add uptime to traefik and watch few youtube videos too but still its not working.

my config on uptime docker-compsoe file is like this:
```
version: "3.8"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.entrypoints=http"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.local.MYDOMAIN`)"
      - "traefik.http.middlewares.uptime-kuma-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.uptime-kuma.middlewares=uptime-kuma-https-redirect"
      - "traefik.http.routers.uptime-kuma-secure.entrypoints=https"
      - "traefik.http.routers.uptime-kuma-secure.rule=Host(`uptime-kuma.local.MYDOMAIN`)"
      - "traefik.http.routers.uptime-kuma-secure.tls=true"
      - "traefik.http.routers.uptime-kuma-secure.service=uptime-kuma"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```

and i even add these to my middlewares in traefik config.yml :
```
default-headers:
      headers:
        sslRedirect: true
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
```
and the log on uptime docker shows this continusly :

```
2024-04-12T14:48:58+03:30 [AUTH] INFO: Username from JWT: admin
2024-04-12T14:48:58+03:30 [AUTH] INFO: Successfully logged in user admin. IP=172.19.0.2
2024-04-12T14:48:59+03:30 [SOCKET] INFO: New polling connection, IP = 172.19.0.2
2024-04-12T14:48:59+03:30 [AUTH] INFO: Login by token. IP=172.19.0.2
2024-04-12T14:48:59+03:30 [AUTH] INFO: Username from JWT: admin
```
but still not working, and i check other issue i found on github but still nothing works and dashboard stuck on infinit loop to connect to socker server

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Microsoft Edge

### 🖥️ Deployment Environment

- Runtime: Docker 26.0
- Database: 
- Filesystem used to store the database on: 
- number of monitors:
