### ISSUE TITLE
Automatic / periodical backups

### ISSUE THREAD

**Issue by jtagcat** [louislam/uptime-kuma#477]
Allow making backups automatically, saving to a specified local storage directory.

Cleanup may be left to the user or implemented with 'keep last n backups'.

**Comment by Mellowor** [comment]
Hi, i would like to try implement this feature, could you assign it to me @louislam ? Also this is one of my first contributions do you have some specific advice beyond the contribution file?

**Comment by louislam** [comment]
> Hi, i would like to try implement this feature, could you assign it to me @louislam ? Also this is one of my first contributions do you have some specific advice beyond the contribution file?

Thank you so much!

But I would not recommend to implement this in the current stage, because the backup is done via the frontend in the current implementation, which means that you have to rewrite the backup feature in backend before you start to implement this feature. I don't think it is an easy task.

Also, as most Uptime Kuma users are able to access the machine, using any existing backup tools such as rsync/zip/cron is more reliable and flexible in my opinion.

**Comment by b-a0** [comment]
If you are using docker you can backup the volume with the data periodically using [the offen/docker-volume-backup image](https://github.com/offen/docker-volume-backup). It can take care of writing to remote storage, pruning old back-ups and sending notifications in case of backup failure.

The full compose file would look something like:

```yml
version: '3'

services:
  uptime:
    container_name: uptime
    image: louislam/uptime-kuma:1
    volumes:
      - uptime-kuma:/app/data
    environment:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - docker-volume-backup.stop-during-backup=true
    restart: always

  backup-kuma:
    container_name: backup-kuma
    image: offen/docker-volume-backup:v2.27.0
    restart: always
    env_file: ./.backup.env
    volumes:
      - uptime-kuma:/backup/uptime-kuma_mount:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/user/backups:/archive
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

With the `.backup.env` containing:

```
BACKUP_ARCHIVE="/archive"
BACKUP_CRON_EXPRESSION="0 0 * * 0"
BACKUP_FILENAME="uptime-backup-%Y-%m-%dT%H-%M-%S.tar.gz"
BACKUP_PRUNING_PREFIX="uptime-backup-"
BACKUP_RETENTION_DAYS="31"
NOTIFICATION_URLS=ntfy://ntfy.sh/example_uptime_backup_topic?title=Uptime%20Kuma%20backup
```

Above example would backup the volume `uptime-kuma` to the location `/home/user/backups` on the docker host, every Sunday at midnight. It would keep backups of the past 31 days, after which it will prune older backups. In case of error it sends a notification via [ntfy.sh](https://ntfy.sh/).

<sub>No affiliation, just a happy user of the volume-backup image.</sub>
