### ISSUE TITLE
[security] Monitoring docker containers

### ISSUE THREAD

**Issue by thielj** [louislam/uptime-kuma#4783]
### 📑 I have found these related issues/pull requests

- https://github.com/louislam/uptime-kuma/issues/2061
- https://github.com/louislam/uptime-kuma/issues/1117

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Access to the docker socket is almost equivalent to a root shell, no matter if the socket is mounted read-only or made available through a (SSL) network connection. Instead of the procedure suggested [in the docs](https://github.com/louislam/uptime-kuma/wiki/How-to-Monitor-Docker-Containers), a much better approach would be to expose the socket through a proxy that makes only the necessary read-only API available to Uptimee Kuma through an internal docker network.

I'm using [Tecnativa/docker-socket-proxy](https://github.com/Tecnativa/docker-socket-proxy) for that purpose. See the docs there.

I'm deliberately reporting this as a "documentation bug" and not a direct vulnerability to Uptime Kuma as it requires the host system or *ANY* container or any other system having access to the exposed socket to be compromised. However, suggesting this to users who are probably unaware of the implications is simply bad practice as it allows an attacker to immediately acquire root privileges.

### 👟 Reproduction steps

```sh
docker -H tcp://127.0.0.1 run -v '/:/mnt' busybox touch /mnt/test
ls -al /test
```

### 👀 Expected behavior

n/a

### 😓 Actual Behavior

n/a

### 🐻 Uptime-Kuma Version

all versions

### 💻 Operating System and Arch

Any Linux

### 🌐 Browser

n/a

### 🖥️ Deployment Environment

Monitoring docker containers

**Comment by louislam** [comment]
I think Portainer did that in the same way.

```
docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
```

May need a reason why Portainer is ok to do that, but Uptime Kuma cannot.

**Comment by CommanderStorm** [comment]
I don't know how to set up this proxying.
I think adding it as a tip to the docs such as

> [!TIP]
> You can reduce your attack surface ...

=> I think this would be valuable.

You seem to have to have the whole thing figured out. Could you provide a PR to enhance https://github.com/louislam/uptime-kuma-wiki/blob/master/How-to-Monitor-Docker-Containers.md?

**Comment by ColCh** [comment]
Thank you very much @thielj for links to tests, much helpful.

I use this approach in my homelab. Might be useful for somebody, may be :)

It uses  [Tecnativa/docker-socket-proxy](https://github.com/Tecnativa/docker-socket-proxy) _Proxy over your Docker socket to restrict which requests it accepts_ 

docker compose for it as follows. Use `http://docker-socket-proxy:2375` as url for docker **TCP/HTTP** connection type 

```yml
services:
    uptime-kuma:
        image: louislam/uptime-kuma:1
        container_name: uptime-kuma
        volumes:
            - ./data:/app/data
        expose:
            - 3001
        restart: always
        labels:
            - 'com.centurylinklabs.watchtower.enable=true'
        cpu_count: 1
        mem_limit: 512m
        security_opt:
          - no-new-privileges:true
        networks:
            - local-int
            - myint

    docker-socket-proxy:
        image: tecnativa/docker-socket-proxy
        container_name: docker-socket-proxy
        healthcheck:
            test: ["CMD", "nc", "-z", "localhost", "2375"]
        restart: always
        environment:
            CONTAINERS: 1 # Allows access to /containers/*
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - local-int
        cpu_count: 1
        mem_limit: 512m
        security_opt:
          - no-new-privileges:true
        expose:
            - '2375'
        labels:
            - 'com.centurylinklabs.watchtower.enable=true' # you might NOT want to use watchtower with this one

networks:
    local-int:
    myint: # your reverse-proxy network
        external: true

```
