### ISSUE TITLE
Prometheus issue: Context Deadline Exceeded

### ISSUE THREAD

**Issue by jmerlos282** [louislam/uptime-kuma#4823]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

I am trying to enabled prometheus endpoint; however, no matter what configuration options I try one of two error messages.

I am not sure what am i doing wrong here.

```yaml
global:
  scrape_interval: 1m
  query_log_file: /prometheus/query.log

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']


  - job_name: 'uptime'
    scrape_interval: 30s
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: ['xxx.xxx.xxx.xxx:3002']
    basic_auth: # Only needed if authentication is enabled (default) 
      username: <xxx>
      password: <xxx>
```

### 📝 Error Message(s) or Log

Get "http://xxx.xxx.xxx.xxx:3002/metrics": context deadline exceeded

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

![image](https://github.com/louislam/uptime-kuma/assets/4823778/bde89ae4-3b46-4b40-b0fd-2725f4ab21d7)
