### ISSUE TITLE
Incorrect username or password

### ISSUE THREAD

**Issue by rucksman** [louislam/uptime-kuma#4828]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I use Uptime Kuma since quite some time. I did not log in for many weeks, but today I wanted to add a new server to monitor. For whatever reason it says "Incorrect username or password". I am very sure that the password is correct. I entered the docker container and did `npm run reset-password` and changed the password to the one that I am sure that I used it also before. Tried to log in: incorrect username or password. `docker logs uptime-kuma` shows no error, also error.log shows no error. What could be wrong here?

### 📝 Error Message(s) or Log

No error message, nothing in error.log

### 🐻 Uptime-Kuma Version

As I cannot log in, all I can say is that I use the latest Docker image

### 💻 Operating System and Arch

Docker in Ubuntu 22.04

### 🌐 Browser

Chrome 125.0.6422.142

### 🖥️ Deployment Environment

- Runtime: Docker 24.0.7
- Database:  sqlite
- Filesystem used to store the database on: ext4
- number of monitors: cannot log in, so my guess is around 10

**Comment by CommanderStorm** [comment]
You closed the issue => you likely found the culprit.

For future documentation: what was the cause?

**Comment by rucksman** [comment]
Not 100% sure, I guess there was a problem with the browser cache. On another laptop there was no problem logging in, and after deleting all cookies and temp files etc. in the other browser, I was able to login there as well.

**Comment by fernvenue** [comment]
Same here, clear the cache and cookie not working for me, and when I use F12 dev tool I just found out that there are no actual requests send to the server.

**Comment by fernvenue** [comment]
This issue still hasn't been resolved. I replicated the problem again today, and in the browser's developer mode, I didn't see any login-related requests; it basically just throws an error directly.

**Comment by aliocha44** [comment]
Hi, I encounter the same problem. Kuma always worked great, but I recently migrate to a new server, where I switched from nginx to Caddy.

I'm using docker for uptime-kuma, behind a Caddy reverse proxy. Here are my files : 
Kuma's docker-compose.yml :
```
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - reverse-proxy
    restart: always

networks:
  reverse-proxy:
    external: true
```
Caddy's docker-compose.yml :
```
services:
  caddy:
    image: caddy:latest
    container_name: caddy-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - reverse-proxy
    restart: always

volumes:
  caddy_data:
  caddy_config:

networks:
  reverse-proxy:
    external: true
```
Caddyfile :
```
kuma.mydomain.com {
        reverse_proxy uptime-kuma:3001
        tls me@mydomain.com
}
```

Login works 1 try of 10. Clear cache and restart container help, but not always. When I refresh kuma's login page, message "Lost connection to the socket server. Reconnecting..." pops really often in red.

I'm quite out of idea to solve this problem, thank you

**Comment by lucasroyerdev** [comment]
**Answer to myself:** I made a silly mistake by running two Kuma servers side by side on the same server. 

Docker-compose.yml files were : 
```
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
```

```
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma-2
```

Container's names is different, but service's names are the same. This causes problems for the reverse proxy, which does not send the identification requests to the correct container.

Correct files with `services: uptime-kuma-2:` : 
```
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
```

```
services:
  uptime-kuma-2:
    image: louislam/uptime-kuma
    container_name: uptime-kuma-2
```
