### ISSUE TITLE
 Socket.<anonymous> (/app/server/server.js:934:17)

### ISSUE THREAD

**Issue by KaMaToZzz** [louislam/uptime-kuma#5010]
### 📑 I have found these related issues/pull requests

Hello, I have some errors in logs of docker container

```
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: TypeError: callback is not a function
    at Socket.<anonymous> (/app/server/server.js:934:17)
    at process.unexpectedErrorHandler (/app/server/server.js:1905:13)
    at process.emit (node:events:517:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: TypeError: callback is not a function
    at Socket.<anonymous> (/app/server/server.js:934:17)
    at process.unexpectedErrorHandler (/app/server/server.js:1905:13)
    at process.emit (node:events:517:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```
### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Im just run latest container, thats all

### 👟 Reproduction steps

Run latest container
```
- name: Start uptime-kuma project with inline definition
  community.docker.docker_compose:
    project_name: uptime_kuma
    definition:
      services:
        uptime-kuma:
          image: louislam/uptime-kuma:1
          container_name: uptime-kuma
          environment:
            SSL_CERT: /app/data/ssl/domain.crt
            SSL_KEY: /app/data/ssl/domain.key
            PORT: 443
          volumes:
            - /src/uptime-kuma-data:/app/data
            - /src/uptime-kuma-data/ssl:/app/data/ssl
          ports:
            - 443:443  # <Host Port>:<Container Port>
          restart: always
```

### 👀 Expected behavior

dont know

### 😓 Actual Behavior

dont know

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

ubuntu 22.04

### 🌐 Browser

safari

### 🖥️ Deployment Environment

- Runtime: containerd
- Database: sqllite
- Filesystem used to store the database on: ext4
- number of monitors: 28
