### ISSUE TITLE
Notification Gotify Server with diffrent port

### ISSUE THREAD

**Issue by neodata83** [louislam/uptime-kuma#5069]
### 📑 I have found these related issues/pull requests

Nothing

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When i run a Gotify Server with the standard port it works fine. But when i change the Port n get errors (See below)

### 👟 Reproduction steps

Ann Server uRL with diffrent port like 10.10.10.10:8080

### 👀 Expected behavior

send a notification

### 😓 Actual Behavior

loop then press test

### 🐻 Uptime-Kuma Version

Version: 1.23.13

### 💻 Operating System and Arch

docker

### 🌐 Browser

chrome and firefox

### 🖥️ Deployment Environment

Docker version 27.1.1, build 6312585

### 📝 Relevant log output

```shell
Error: Error: Error: connect ETIMEDOUT 192.168.1.213:3080 
at Gotify.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:38:15)
at Gotify.send (/app/server/notification-providers/gotify.js:23:18)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Socket.<anonymous> (/app/server/server.js:1304:27)
```

**Comment by CommanderStorm** [comment]
Could you please share further details about your setup?
How have you set up gotify speciifcally, what is your docker-compose command?
How did you configure the notification provider?

**Comment by neodata83** [comment]
Sure. I ran OMV7 as Main host with 2nics. Gotify container runs in Bridge Mode from NIC1 with different port because Port80 is in use. Uptime Kuma Container Runs on NIC2 with MCVLAN so that it gets its own ip Address. 

Gotify Container docker-compose
```
version: '3.1'

services:     
  Gotify:
      image: gotify/server
      container_name: Gotify
      environment:
        - TZ=Europe/Berlin

      volumes:
        - gotify-data:/app/data
      ports:
        - 3080:80
        - 3443:443
      restart: unless-stopped
     
volumes:
  gotify-data:
    external: true
```
Uptime Kuma docker-compose

```
version: '3.1'
networks:
    nic2-lan:
     external: true

services:     
  Gotify:
      networks: 
        nic2-lan:
          ipv4_address: 192.168.1.21
      image: louislam/uptime-kuma
      container_name: uptime-kuma
      environment:
        - TZ=Europe/Berlin

      volumes:
        - uptimekuma-data:/app/data
      ports:
        - 3001:3001
      tty: true
      stdin_open: true
      restart: unless-stopped
     
volumes:
  uptimekuma-data:
    external: true
```

Config Gotify Server with port

![floorp_563vuSwCP3](https://github.com/user-attachments/assets/b2437011-634a-420e-9072-84d57c63d367)
