### ISSUE TITLE
Trying to create ingress type of aws alb ,also adds default annotations set in helm chart

### ISSUE THREAD

**Issue by taragurung** [louislam/uptime-kuma#5082]
### 📑 I have found these related issues/pull requests

Related to ingress no provisioned after doing necessary changes in helm chart values and upgrading the chart

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I am having issues setting up ingress using helm chart, when setting up ingress it also adds the default annotations which I don't require.

### 👟 Reproduction steps

- install uptime kuma --version 2.19.3
- make changes to setup ingress as follows:
```
ingress:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:8xxxx:certificate/c13250b9-xxxx-xxx-8xx-xxxaca8a40
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
  enabled: true
  ingressClass: alb
  extraLabels: {}
  hosts:
  - host: uptime.mywebsite.com
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
```
run helm upgrade command with above changes

### 👀 Expected behavior

Ingress setup successful 

### 😓 Actual Behavior

- Ingres is not provisioned 
- also getting bellow annotations when checking the ingress with describe
```
nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
                            nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
                            nginx.ingress.kubernetes.io/server-snippets:
                              location / {
                                proxy_set_header Upgrade $http_upgrade;
                                proxy_http_version 1.1;
                                proxy_set_header X-Forwarded-Host $http_host;
                                proxy_set_header X-Forwarded-Proto $scheme;
                                proxy_set_header X-Forwarded-For $remote_addr;
                                proxy_set_header Host $host;
                                proxy_set_header Connection "upgrade";
                                proxy_set_header X-Real-IP $remote_addr;
                                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                                proxy_set_header   Upgrade $http_upgrade;
                                proxy_cache_bypass $http_upgrade;
                              }
Events:                     <none>
```

### 🐻 Uptime-Kuma Version

2.19.3

### 💻 Operating System and Arch

Debian-12

### 🌐 Browser

Google chrome

### 🖥️ Deployment Environment

- Runtime:  K8s  v1.29.6-eks-db838b0
helm chart used for deployment and upgrades

### 📝 Relevant log output

```shell
this is the controller logs that creates alb 
{"level":"error","ts":"2024-09-03T15:25:39Z","msg":"Reconciler error","controller":"ingress","object":{"name":"uptime-kuma","namespace":"uptime-kuma"},"namespace":"uptime-kuma","name":"uptime-kuma","reconcileID":"0b6c6cba-7257-4e49-ac1b-7fc5f2032492","error":"Ingress.networking.k8s.io \"uptime-kuma\" not found"}
```
