### ISSUE TITLE
BUG: Docker Container Crash and UnhandledPromiseRejectionWarning Error

### ISSUE THREAD

**Issue by tucker19** [louislam/uptime-kuma#51]
Been running this a few days within my Docker stack with 17 other containers. After starting up my container I see this in my logs
```
> uptime-kuma@1.0.4 start-server /app
> node server/server.js

Copy Database

Connect to Database

JWT secret is not found, generate one.

(node:18) UnhandledPromiseRejectionWarning: Error: SELECT COUNT(*) FROM `user`  limit 1 - SQLITE_CORRUPT: database disk image is malformed

(Use `node --trace-warnings ...` to show where the warning was created)

(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
Where is the DB stored for this container as it is not in the config directory I specified either.

**Comment by tucker19** [comment]
This is running on Ubuntu and Docker 2.4

**Comment by louislam** [comment]
It looks your sqlite db is corrupted. You may try to repair it.
The db is located at "/app/data/kuma.db". It should be binding to your volume.

**Comment by tucker19** [comment]
Thank you for getting back with me. I have tried doing a exec into the container and I am seeing a error
$docker exec -it uptime-kuma /bin/bash
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown

I try this same command on other containers and it works fine. I cannot find this directory you have stated to either delete the db or repair it.

**Comment by rezzorix** [comment]
@tucker19 you got the docker exec error because you need to go into /bin/sh instead of /bin/bash

`docker exec -it uptime-kuma /bin/sh`

**Comment by tucker19** [comment]
@rezzorix Thank you for that info. Never really used /bin/sh, I have only ever used /bin/bash. I am actually using Docker-Compose file for this and I do have a Volume in there but this container never puts anything in there 
```
uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - 3001:3001
    volumes:
      - $DOCKER_PATH/uptime-kuma/config:/config
    restart: unless-stopped
```
Do I need to change this to something different?

**Comment by rezzorix** [comment]
> I do have a Volume in there but this container never puts anything in there

`- $DOCKER_PATH/uptime-kuma/config:/config`

Well the data folder of uptime-kuma is /app/data

So you need to change to this:

```
uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - 3001:3001
    volumes:
      - $DOCKER_PATH/uptime-kuma/config:/app/data
    restart: unless-stopped
```
Anyway, make sure that the path `$DOCKER_PATH/uptime-kuma/config` exists and the read/write permissions are set
