### ISSUE TITLE
Help with Installing Apprise

### ISSUE THREAD

**Issue by yodaphone** [louislam/uptime-kuma#5170]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to enable notifications via Apprise & when i selected it, i get this "Status: Apprise is not installed. [Read more](https://github.com/caronc/apprise)"

When i click on that link it says to install apprise with "pip install apprise"

I am not well versed with this, but i have uptime kuma running in a docker container.

can you please help me with the steps to install apprise?

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

Ubuntu 22.04 running Docker

### 🌐 Browser

Brave Version 1.70.123 Chromium: 129.0.6668.89

### 🖥️ Deployment Environment

Docker compose

```
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.15
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
```

**Comment by yodaphone** [comment]
Hi
this is the screenshot from my install
![image](https://github.com/user-attachments/assets/cd6efaf2-d6c4-410a-b096-35c814c2902a)

Its enabled in Live Demo though
![image](https://github.com/user-attachments/assets/4001da4c-604d-47bd-bf60-1ee814c8a681)

Since this is running in a docker VM that runs other containers as well, can there be a conflict with a port number?

**Comment by yodaphone** [comment]
Sorry, i more thing i forgot to add, I'm running the container with a cloudflare reverse proxy. 

```
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.15
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always

  cloudflared: 
    image: cloudflare/cloudflared 
    container_name: cloudflare-tunnel 
    restart: unless-stopped 
    command: tunnel run 
    environment: 
      - TUNNEL_TOKEN=xxxxxxxxxxxxxxxxxxxxxxx
```

I just ran another instance without that and apprise was showing as installed.

```
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.15
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
```
