### ISSUE TITLE
Remove uptime %

### ISSUE THREAD

**Issue by OiziZ** [louislam/uptime-kuma#5216]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

It's possible to remove or replace the number and % ?
I see it's possible to do some custom css.
![Capture d’écran du 2024-10-18 11-00-17](https://github.com/user-attachments/assets/59b3bd97-fb18-4de8-a01b-921f7f89b87a)

Thanks
Best Regards

### 📝 Error Message(s) or Log

No a error

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

Ubuntu server 24.04 LTS

### 🌐 Browser

Firefox 131.0.2

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by OiziZ** [comment]
![Capture d’écran du 2024-10-18 11-00-17](https://github.com/user-attachments/assets/9e328622-a49c-409e-9ae9-ef62137c9a04)

**Comment by cyril59310** [comment]
```css
.badge.rounded-pill.bg-secondary,
.badge.rounded-pill.bg-primary,
.badge.rounded-pill.bg-danger,
.badge.rounded-pill.bg-warning {
    display: none;
}
```

This will remove the percentage for all the states of the monitor.
![image](https://github.com/user-attachments/assets/1c599009-01bc-40fa-b37d-684275c27128)
