### ISSUE TITLE
Status Page Custom CSS Help

### ISSUE THREAD

**Issue by syncblaze** [louislam/uptime-kuma#5335]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Im working on a custom css for my status page. Mainly i want to edit the Colors.

I dont understand what to change, so that the color change hover effect of monitors has a different color.
If you dont know what i mean take a look here:
https://github.com/user-attachments/assets/3f3930b7-5128-41dd-a296-dca2b83cf82c

### 📝 Error Message(s) or Log

Custom CSS:
```css
.dark {
background-color: #060400;
}
.item:hover {
  background-color: #0d0900;
}

.dark .shadow-box:not(.alert) {
    background-color: #0d0900;
}
```

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:
