### ISSUE TITLE
Negative respond time??

### ISSUE THREAD

**Issue by Tobydog0501** [louislam/uptime-kuma#5395]
### 📑 I have found these related issues/pull requests

I can't find any related issues

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hi, I found that sometimes, my sevice, which isn't running on my local network,  respond with negative lantency.
![image](https://github.com/user-attachments/assets/d6c33ee3-6d80-4f02-805d-aa56c6c57055)
I'm not pretty sure if this is a bug or just my configuration problem.
This is my docker-compose file
```
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: always
    networks:
    - cloudflared_tunnel


networks:
  cloudflared_tunnel:
    external: true
```

### 👟 Reproduction steps

I really dont know how and why this is happening.

### 👀 Expected behavior

I think there shouldn't be any negative lantency

### 😓 Actual Behavior

The lantency is negative.

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

Docker Container

### 🌐 Browser

Chrome/128.0.0.0

### 🖥️ Deployment Environment

- Runtime: Docker version 27.2.0,
- Database:  local storage?
- Filesystem used to store the database on:  Windows
- number of monitors: 6
