### ISSUE TITLE
Enable mDNS resolution in docker container

### ISSUE THREAD

**Issue by derekoharrow** [louislam/uptime-kuma#5400]
### 📑 I have found these related issues/pull requests

None found.

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Many devices now use mDNS for .local hostname resolution. It appears that Uptime Kuma cannot resolve these and that an mDNS resolver is not installed within the container, so you either have to hard-code IP addresses, or setup these devices in DNS.

### ✔️ Solution

As part of the Dockerfile, install libnss-mdns, and configure mDNS (nsswitch.conf) - e.g.

```
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    libnss-mdns \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i 's/hosts:.*/hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4/' /etc/nsswitch.conf

```

**Comment by thislooksfun** [comment]
I would also love this. In the meantime I have found a workaround. All you have to do is install avahi in the image then mount `/var/run/dbus` and `/var/run/avahi-daemon/socket`. Here is an example using a compose file:

```Dockerfile
# File: Dockerfile
FROM louislam/uptime-kuma:2-slim

# Install avahi so that mDNS can resolve .local domains
RUN apt-get update && apt-get install avahi-utils -y
```

```yaml
# File: compose.yml
services:
  uptime-kuma:
    container_name: uptime-kuma
    build: .
    restart: unless-stopped
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    ports:
      - "3001:3001"
```
