### ISSUE TITLE
How to setup uptime-kuma sent metrics to google managed service for prometheus?

### ISSUE THREAD

**Issue by xpo-mie** [louislam/uptime-kuma#5451]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Now, I'm setup uptime-kuma on GKE cluster and need to get metrics from google managed service for prometheus (GMP). basically , we can use podmonitoring of google monitoring API as example as below;
```
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: uptime
  namespace: monitoring
  labels:
    app.kubernetes.io/name: uptime
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  endpoints:
  - port: 3001
    scheme: http
    interval: 30s
    path: /metrics
    basicAuth: 
      password:
        secret:
          name: uptime
          key: password
  selector:
    matchLabels:
      app.kubernetes.io/name: uptime
```

### 📝 Error Message(s) or Log

After apply this and verify on GMP by promql "up{job="uptime"}" result its shown "0

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

k8s

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:
