### ISSUE TITLE
Internal HTTP Sites Monitoring Failure using NTLM

### ISSUE THREAD

**Issue by hanogin** [louislam/uptime-kuma#5500]
### 📑 I have found these related issues/pull requests

#https://github.com/louislam/uptime-kuma/issues/4550

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Unable to establish monitoring connections to internal HTTP (HTTPS is working!) sites using Uptime Kuma, the site use NTLM authentication/anonimus (ntlm configured properly in the monitor settings). While these sites are accessible via browser with NTLM credentials/anonimus, the monitor fails to establish connections.

Current Configuration: docker-compose.yml

```
version: '1'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
```
Connections over HTTPS working fine!

### 👟 Reproduction steps

1. Deploy Uptime Kuma using provided docker-compose.yml
2. Access Uptime Kuma dashboard at http://localhost:3001/
3. Add new monitor with following settings:

- Type: HTTP
- URL: Internal site URL (http://internal-site/)
- Authentication: NTLM
- Username: [domain\username]
- Password: [password]

4. Save monitor configuration
5. Observe immediate failure with ENOTFOUND error
6. Verify same URL works in browser with same credentials

### 👀 Expected behavior

Expected the connection to work over HTTP and HTTPS event without the need to configure 
`NODE_OPTIONS=--openssl-legacy-provider`

### 😓 Actual Behavior

HTTP site wont work
recive the error:
```
'sitename - TEST - GUI': Failing: getaddrinfo ENOTFOUND sitename-test |
Interval: 60 seconds | Type: http | Down Count: 0 | Resend Interval: 0
```
HTTPS working only with ``NODE_OPTIONS=--openssl-legacy-provider`` in yml file

### 🐻 Uptime-Kuma Version

1

### 💻 Operating System and Arch

windows 10

### 🌐 Browser

Google Chrome  131.0.6778.205

### 🖥️ Deployment Environment

- Runtime:  Docker Desktop on Windows 10
- Database: default embedded
- Filesystem used to store the database on: Windows
- number of monitors: 10-20
- Target Servers: Windows Server with IIS
- Authentication: Windows Authentication enabled on IIS

### 📝 Relevant log output

```shell
'sitename - TEST - GUI': Failing: getaddrinfo ENOTFOUND sitename-test |
Interval: 60 seconds | Type: http | Down Count: 0 | Resend Interval: 0
```
```
