### ISSUE TITLE
Discord Webhook Service URL

### ISSUE THREAD

**Issue by RejectModders** [louislam/uptime-kuma#5536]
### ⚠️ Please verify that this question has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I did find similar issues, but they were never fully answered or never has a conclusion, I am asking is there any way to just get rid of the Service URL, it contains sensitive information, it should truly be based on when you setup the status page. You have the option of allowing the link being clickable or not, or you can just go off an option in the dashboard, it can go either way, but I truly need to get the service URL off the embed some how, you can do custom Webhooks, but it is not working. 

### 🐻 Uptime-Kuma Version

1.23.16

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Brave v 1.73.105 / [Chrome 131](https://www.whatismybrowser.com/detect/what-version-of-chrome-do-i-have/)

### 🖥️ Deployment Environment

- Runtime: Docker 27.41
- Database: sqlite 
- Filesystem used to store the database on: ext4
- number of monitors: 10

**Comment by cyril59310** [comment]
I was in the same situation as you. To solve this issue, I created a `notification-providers folder` and downloaded the `discord.js` file from https://github.com/louislam/uptime-kuma/blob/master/server/notification-providers/discord.js, which handles the Discord notification. I modified it to remove the URL in the code and mounted it as a volume on my Docker container to replace the current notification

```
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./data/:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./notification-providers/discord.js:/app/server/notification-providers/discord.js
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
```
