### ISSUE TITLE
Docker compose update erased the database

### ISSUE THREAD

**Issue by brunoamaral** [louislam/uptime-kuma#5549]
### ⚠️ Please verify that this question has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Maybe this was a miss step on my part.

docker-compose.yaml
```
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - "3002:3001"
    restart: always
```

Then when updating with `docker compose pull`, `docker compose up -d` the container was recreated and the database left blank.

### 🐻 Uptime-Kuma Version

1.23.16

### 💻 Operating System and Arch

Ubuntu 22.04.5

### 🌐 Browser

Any

### 🖥️ Deployment Environment

- Runtime: Docker version 27.4.0, build bde2b89
- Database: sqlite
- Filesystem used to store the database on: ext4
- number of monitors: 5 - 7.
