### ISSUE TITLE
Docker compose.yaml missing ipv6 support

### ISSUE THREAD

**Issue by neilbags** [louislam/uptime-kuma#5676]
### 📑 I have found these related issues/pull requests

I can't see any reporting ipv6 issue with the docker container where docker ipv6 is otherwise configured and working

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I'm using uptime-kuma from the latest docker image:
```
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
```
Docker ipv6 is configured:
```
# cat /etc/docker/daemon.json
{
  "ipv6": true,
  "fixed-cidr-v6": "<hidden>"
}
```
Docker ipv6 is working:
```
# docker run --rm -it busybox ping -c 1 ipv6.google.com
PING ipv6.google.com (2404:6800:4006:814::200e): 56 data bytes
64 bytes from 2404:6800:4006:814::200e: seq=0 ttl=116 time=0.945 ms
```
ipv6 in the uptime-kuma container is not:
```
# docker exec uptime-kuma ping -c 1 ipv6.google.com
connect: Network is unreachable
```
Have tested on multiple hosts, Ubuntu 24.04 and 22.04.

### 👟 Reproduction steps

```
docker exec uptime-kuma ping -c 1 ipv6.google.com
```

### 👀 Expected behavior

ipv6 works

### 😓 Actual Behavior

```
connect: Network is unreachable
```

### 🐻 Uptime-Kuma Version

1.23.16

### 💻 Operating System and Arch

Ubuntu 24.04

### 🌐 Browser

Firefox 135.0.1

### 🖥️ Deployment Environment

Default docker image

### 📝 Relevant log output

```shell

```

**Comment by CommanderStorm** [comment]
```
docker exec uptime-kuma ping -c 1 ipv6.google.com
connect: Network is unreachable
```

If ipv6.google.com is not reachable from the docker container, this is not our fault.
There is something wrong with how you set up the networking => start with the midpoint, look if pinging works => bisect your network from there..

Setting docker up to support ipv6 can be tricky

Closing as resolved as not an issue in our docker image

**Comment by neilbags** [comment]
@CommanderStorm I had another look at this - ipv6 was enabled and working in docker but it appears that it needs to be explicitly enabled in the compose file. i.e. this works:
```yaml
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: unless-stopped
    networks:
      - uptime-kuma
networks:
  uptime-kuma:
    enable_ipv6: true
```
The provided one doesn't work (at least on my systems) and I can't see any way to enable it globally. Do you want me to submit a PR to update the provided compose.yaml?
