### ISSUE TITLE
Unable to verify the first certificate (wildcard cert from GoDaddy)

### ISSUE THREAD

**Issue by ericciccone** [louislam/uptime-kuma#5748]
### ⚠️ Please verify that this question has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have a dev/prod instance of Uptime. The VMs are identical, including the docker-compose.yaml. Upon spinning up Uptime in prod, a server that uses a wildcard cert from GoDaddy receives the "unable to verify the first certificate" error. In dev, this is not an issue. What's odd is that using `openssl s_client -showcerts -connect jama.bluecanyontech.com -port 443` - both servers are not able to verify the first cert, but in dev Uptime, it lists the full chain. 

I downloaded the cert from GoDaddy and placed it in usr/local/share/ca-certificates, ran update-ca-certificates, no change.

Uptime is able to determine the expiry of the first cert.

### 📝 Error Message(s) or Log

```
$openssl s_client -showcerts -connect jama.[domain].com -port 443
CONNECTED(00000003)
depth=0 CN = *.[domain.com]
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = *.[domain.com]
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN = *.[domain.com]
verify return:1No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
```
---
```
SSL handshake has read 2233 bytes and written 405 bytes
Verification error: unable to verify the first certificate

2025-04-02T12:41:51-06:00 [MONITOR] WARN: Monitor #9 'Jama': Failing: unable to verify the first certificate | Interval: 60 seconds | Type: http | Down Count: 0 | Resend Interval: 0
```

docker-compose.yaml
```
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.15
    environment:
      - TZ=America/Denver
      - NODE_EXTRA_CA_CERTS=/certs/local-certificate-authority.pem
    volumes:
      - ./data:/app/data
      - /usr/local/share/ca-certificates:/certs:ro
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: unless-stopped
volumes:
  data:
    external: true
```

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

Ubuntu 22.04 x86_64

### 🌐 Browser

Chrome 134.0.6998.88

### 🖥️ Deployment Environment

- Runtime: Docker 28.0.4 build b8034c0 / nodejs v18.20.3 / 
- Database: default
- Filesystem used to store the database on: Ubuntu SDA
- number of monitors: 27
