### ISSUE TITLE
ERROR: Failed to prepare your database:

### ISSUE THREAD

**Issue by RSaikiranGoud** [louislam/uptime-kuma#5754]
### ⚠️ Please verify that your question has not already been reported

- [x] I have searched the [existing issues](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue%20sort%3Acreated-desc%20) and found no similar reports.

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Describe your problem

We are working on getting uptimekuma deployed with external managed mariadb operator but it throws error with 

please find the deployment file 👍 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uptimekuma
    app.kubernetes.io/instance: uptimekuma
  name: uptime-kuma
  namespace: gssmon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptimekuma
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uptimekuma
    spec:
      containers:
      - image: louislam/uptime-kuma:2.0.0-beta.1
        imagePullPolicy: IfNotPresent
        name: uptime-kuma
        ports:
        - containerPort: 3001
          protocol: TCP
        env:
        - name: UPTIME_KUMA_DB_HOST
          value: "mariadb-galera.mariadb-cluster.svc"
        - name: UPTIME_KUMA_DB_PORT
          value: "3306"
        - name: UPTIME_KUMA_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: uptime-kuma-db-secret
              key: DB_USERNAME
        - name: UPTIME_KUMA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: uptime-kuma-db-secret
              key: DB_PASSWORD
        - name: UPTIME_KUMA_DB_DATABASE
          value: "uptime"
        - name: UPTIME_KUMA_DB_TYPE
          value: "mariadb"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
```

### 📝 Error Message(s) or Log

```bash session
Welcome to Uptime Kuma
Your Node.js version: 20.18.0
2025-04-04T17:29:52Z [SERVER] INFO: Env: production
2025-04-04T17:29:55Z [SERVER] INFO: Uptime Kuma Version: 2.0.0-beta.1
2025-04-04T17:29:55Z [SERVER] INFO: Loading modules
2025-04-04T17:29:58Z [SERVER] INFO: Creating express and socket.io instance
2025-04-04T17:29:58Z [SERVER] INFO: Server Type: HTTP
2025-04-04T17:29:59Z [SERVER] INFO: Data Dir: ./data/
2025-04-04T17:29:59Z [SETUP-DATABASE] INFO: db-config.json is not found or invalid: ENOENT: no such file or directory, open 'data/db-config.json'
2025-04-04T17:29:59Z [SETUP-DATABASE] INFO: UPTIME_KUMA_DB_TYPE is provided by env, try to override db-config.json
2025-04-04T17:29:59Z [DB] INFO: Database Type: mariadb
2025-04-04T17:29:59Z [SERVER] ERROR: Failed to prepare your database:
```

### 🐻 Uptime-Kuma Version

2.0.0-beta.1

### 💻 Operating System and Arch

kubernetes 1.31.

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

- **Runtime Environment**:
  - Docker: Version `X.X.X` (Build `Y.Y.Y`)
  - Docker Compose: Version `X.X.X`
  - Portainer (BE/CE): Version `X.X.X` (LTS: Yes/No)
  - MariaDB: Version `X.X.X` (LTS: Yes/No)
  - Node.js: Version `X.X.X` (LTS: Yes/No)
  - Kubernetes (K3S/K8S): Version `X.X.X` (LTS: Yes/No, via `[method/tool]`)
- **Database**:
  - SQLite: Embedded
  - MariaDB: Embedded/External
- **Database Storage**:
  - **Filesystem**:
    - Linux: ext4/XFS/Btrfs/ZFS/F2FS
    - macOS: APFS/ HFS+
    - Windows: NTFS/ReFS
  - **Storage Medium**: HDD/eMMC/SSD/NVMe
- **Uptime Kuma Setup**:
  - Number of monitors: `X`
