### ISSUE TITLE
Reverse proxy broken (`ERR_TOO_MANY_REDIRECTS 308` on Chrome)

### ISSUE THREAD

**Issue by vwxyzjn** [louislam/uptime-kuma#610]
**Is it a duplicate question?**
Don't think so.

**Describe the bug**
With the latest `louislam/uptime-kuma:1.7.3-alpine` docker container, reverse proxy can no longer be used and the following error appears with both `caddy` and `https-portal`.

![image](https://user-images.githubusercontent.com/5555347/136628521-1f97d89c-25de-4744-87d4-92e420ce1287.png)

By reverting to `louislam/uptime-kuma:1.6.0-alpine` resolves this issue:

![image](https://user-images.githubusercontent.com/5555347/136628719-e6a96267-182c-47bc-8cef-fcf01febcd3d.png)

**To Reproduce**

Run the following `docker-compose.yaml` file:

```yaml
version: '3.3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - uptime-kuma
    restart: always
    environment:
      DOMAINS: 'example.com -> http://uptime-kuma:3001'
      STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
      WEBSOCKET: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal

  uptime-kuma:
    image: louislam/uptime-kuma:1.7.3-alpine
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - 3001:3001

volumes:
  https-portal-data:
```

**Info**
Uptime Kuma Version: 1.7.3
Using Docker?: Yes
Docker Version: 20.10.8
OS: Centos 8
Browser: chrome, safari
