### ISSUE TITLE
iperf3 checker

### ISSUE THREAD

**Issue by MichelBaie** [louislam/uptime-kuma#744]
Check every hour a speedtest using iperf.
If its lower than xxmbps then down.

**Comment by markdesilva** [comment]
Speedtest using iperf from where to where? From the UK server to your own server? Not practical if the UK server is not on your own network I think? Especially if the UK server is not on your network (ideal case). 

If UK server is on your network, then it can be accomplished by running your iperf in daemon mode on the UK server and then setting up a push monitor on the server you are monitoring execute iperf client connections to the UK server, scrap the bandwidth from the results and check if its acceptable and if acceptable then notify the UK server via the push URL. Cron this for every hour and set your monitor time to 3600 seconds.

-- On UK server, run iperf in daemon mode --

`iperf -D -s -w 64k`

-- On server you want to check, create this shell script --

```
#!/bin/sh

acceptable="900"

mbps=`iperf -c <FQDN or IP of uptime kuma server> -w 64k -i 1 -t 1 | tail -1 |cut -d" " -f14`

if [ $mbps -lt $acceptable ]; then
   curl -k -s "https:/uptime.kuma.server/api/push/alkdsfjasd?msg=OK&ping=$mbps"
fi
```
and save it as iperfcheck.sh

Then set your crontab to this

`0 * * * * <path to>/iperfcheck.sh`

Replace "https:/uptime.kuma.server/api/push/alkdsfjasd?msg=OK&ping=" with the push URL from your UK monitor push settings.

**Comment by markdesilva** [comment]
> @markdesilva's solution is a good example for odd monitoring situations like these. It may be worth adding it or something similar to the wiki for future reference.

Speaking of which. how do I add wiki pages? The wiki says its editable but I don't see how to add to it?

**Comment by 2-click** [comment]
Natively monitoring network and internet speeds would sound awsome.

**Comment by Prisoner2-6-7** [comment]
If user wanted to monitor their internet speed then they can fast --upload --json. but they have to install https://github.com/sindresorhus/fast-cli

**Comment by hadifarnoud** [comment]
iperf check would be awesome and useful. let the user set up iperf server and Uptime Kuma use iperf as client only

**Comment by jo-chemla** [comment]
To connect uptime-kuma with [alexjustesen/speedtest-tracker](https://github.com/alexjustesen/speedtest-tracker), one can use a:
```yaml

Monitor: JSON Query 
URL: http://speedtest-tracker-fqdn:port/api/v1/results/latest
Json Query: (data.download_bits > 500000000) and (data.upload_bits > 500000000)
Expected Value: true
Headers:  {"Accept": "application/json", "Authorization": "Bearer your-speedtest-tracker-token" }

```
