### ISSUE TITLE
[Help]: Importing CA certs not working?

### ISSUE THREAD

**Issue by causalityloop** [louislam/uptime-kuma#850]
### 📝 Describe your problem

I am looking to use import a root ca for my self signed certs but something appears to be amiss. After configuring my docker-compose file here: https://github.com/louislam/uptime-kuma/issues/21#issuecomment-881757886 ... I will get certificate validation failures. My compose file is below

```
---
version: "3"
services:
  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022  # optional
      - NODE_EXTRA_CA_CERTS=/certs/KernelDump-Root-CA.crt
    volumes:
      - ./data:/app/data
      - /usr/local/share/ca-certificates:/certs:ro
    ports:
        - 3001:3001
    restart: unless-stopped

```
Error message on one host I "unchecked" the ignore tls errors on to have it verify show ...

`Monitor #23 'ESXi Web': Failing: unable to verify the first certificate | Interval: 20 seconds | Type: http`

The startup log before it starts running checks show ...

```
docker logs kuma
==> Performing startup jobs and maintenance tasks
==> Starting application with user 1000 group 1000
Welcome to Uptime Kuma
Node Env: production
Importing Node libraries
Importing 3rd-party libraries
Importing this project modules
Prepare Notification Providers
Version: 1.10.0
Creating express and socket.io instance
Server Type: HTTP
Data Dir: ./data/
Connecting to the Database
SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
SQLite Version: 3.36.0
Connected
Your database version: 10
Latest database version: 10
Database patch not needed
Database Patch 2.0 Process
Load JWT secret from database.
Adding route
Adding socket handler
Init the server
Listening on 3001
Username from JWT: admin
Username from JWT: admin

```

For giggles, i exec'd into the container and ran openssl to verify the cert for "esxi web" and it also fails

`openssl s_client -connect 192.168.0.13:443`

```
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID:
    Session-ID-ctx:
    Master-Key: ACE80F7B3D8F4C30DCAB2B0A8596BF5D20B422E478F02EF5CD8B5FDDD21397BADCF92CCAD1036AA7E90C123C2C74BE5A
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1635719241
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: no

```

which also matches the error kuma reports. Now, if i copy the ca to /usr/local/share/ca-certficates and run update-ca-certificates ...then openssl reports back a valid cert but kuma still does not recognize it. I also tried doing a "docker restart kuma" but that did not help either

```
root@52902be93781:/app# cp /certs/* /usr/local/share/ca-certificates/
root@52902be93781:/app# update-ca-certificates
Updating certificates in /etc/ssl/certs...
3 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```

openssl output from same command...

```
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID:
    Session-ID-ctx:
    Master-Key: 882C093BC603A603EDC023CFBDFD90DEE1BA45B651530C96CD401B719A99F35DD086DD3B645CCFAA8E0AFFFD8CFA47A3
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1635719450
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
```

### 🐻 Uptime-Kuma version

1.10

### 💻 Operating System

ubuntu 21.10

### 🌐 Browser

brave

### 🐋 Docker

20.10.7

### 🏷️ Docker Image Tag

sha256:451da881cd8964f5542bc1f3bc0e197fc818423f8dd35a5d98458311f2ad18df

### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar question

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)
