### ISSUE TITLE
Check local containers

### ISSUE THREAD

**Issue by simphide** [louislam/uptime-kuma#921]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How do I configure the container so it can access published ports of other containers?

I know that I can use network mode: host or put all containers in one network, but is there another way like granting a cap or something else?

Current compose file:
```
# Simple docker-composer.yml
# You can change your port or volume location

version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - ./app-data:/app/data
    #ports:
    #  - 3001:3001
    network_mode: host # for communicating with local containers
    dns:
      - 1.1.1.2
    restart: unless-stopped
```

Thanks in advance!

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome 95.0.4638.69 

### 🐋 Docker Version

20.10.10

### 🟩 NodeJS Version

-
